In [4]:
import pandas as pd
df=pd.read_csv('pargi_voters_natural_full_uploaded.csv',usecols=['age','gender','household_size','distance_from_assigned_polling_booth_km','voted_status'])
df.head()

,age,gender,household_size,distance_from_assigned_polling_booth_km,voted_status
0,61,Female,5.0,2.83,1
1,22,Female,8.0,2.92,0
2,21,Female,7.0,2.25,0
3,25,Male,6.0,1.49,0
4,77,Male,5.0,1.46,1

In [5]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['voted_status']=lb.fit_transform(df['voted_status'])
df.head()

,age,gender,household_size,distance_from_assigned_polling_booth_km,voted_status
0,61,Female,5.0,2.83,1
1,22,Female,8.0,2.92,0
2,21,Female,7.0,2.25,0
3,25,Male,6.0,1.49,0
4,77,Male,5.0,1.46,1

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

In [7]:
df.head()

,age,gender,household_size,distance_from_assigned_polling_booth_km,voted_status
0,61,0,5.0,2.83,1
1,22,0,8.0,2.92,0
2,21,0,7.0,2.25,0
3,25,1,6.0,1.49,0
4,77,1,5.0,1.46,1

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df = pd.DataFrame(
    scaler.fit_transform(df[['age','household_size', 'distance_from_assigned_polling_booth_km']]),
    columns=['age','household_size', 'distance_from_assigned_polling_booth_km']
)



df.head()

        age  household_size  distance_from_assigned_polling_booth_km
0  0.671454        0.295506                                 0.993576
1 -1.285258        2.133729                                 1.115015
2 -1.335430        1.520988                                 0.210964
3 -1.134742        0.908247                                -0.814527
4  1.474207        0.295506                                -0.855007

In [9]:
df['gender']=df1['gender'].values

In [10]:
df.head()

        age  household_size  distance_from_assigned_polling_booth_km  gender
0  0.671454        0.295506                                 0.993576  Female
1 -1.285258        2.133729                                 1.115015  Female
2 -1.335430        1.520988                                 0.210964  Female
3 -1.134742        0.908247                                -0.814527    Male
4  1.474207        0.295506                                -0.855007    Male

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])
df['voted_status']=df1['voted_status']

In [17]:
df.head()
df=df.dropna()

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
X = df.drop('voted_status', axis=1)
y = df['voted_status']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

accuracy_score(y_test, y_pred)

0.8641876341444493

In [19]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
clf2=RandomForestClassifier(criterion='gini',max_depth=8,min_samples_split=5,min_samples_leaf=9,n_estimators=42,bootstrap=False,oob_score=False,random_state=42)
clf2.fit(X_train,y_train)
ypred3=clf2.predict(X_test)
accuracy_score(ypred3,y_test)

0.8661012127951178

In [20]:
import joblib

joblib.dump(clf2, 'random_forest_model.pkl')

['random_forest_model.pkl']

In [21]:
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']