In [55]:
import numpy as np
import pandas as pd
from sklearn import set_config
set_config(transform_output="pandas")
import matplotlib.pyplot as plt

In [56]:
df=pd.read_csv('pargi_voters_1000_natural_complete.csv',usecols=['age','gender','household_size','distance_from_assigned_polling_booth_km','voted_status'])

In [57]:
df.columns
df1=df

In [58]:
df1.head()

,age,gender,household_size,distance_from_assigned_polling_booth_km,voted_status
0,51,Male,5,1.51,1
1,27,Male,5,1.11,1
2,65,Female,5,1.82,1
3,54,Female,4,2.60,1
4,67,Male,6,4.60,0

In [59]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['voted_status']=lb.fit_transform(df['voted_status'])
df.head()

,age,gender,household_size,distance_from_assigned_polling_booth_km,voted_status
0,51,Male,5,1.51,1
1,27,Male,5,1.11,1
2,65,Female,5,1.82,1
3,54,Female,4,2.60,1
4,67,Male,6,4.60,0

In [60]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

In [61]:
df.head()

,age,gender,household_size,distance_from_assigned_polling_booth_km,voted_status
0,51,1,5,1.51,1
1,27,1,5,1.11,1
2,65,0,5,1.82,1
3,54,0,4,2.60,1
4,67,1,6,4.60,0

In [62]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df = pd.DataFrame(
    scaler.fit_transform(df[['age','household_size', 'distance_from_assigned_polling_booth_km']]),
    columns=['age','household_size', 'distance_from_assigned_polling_booth_km']
)



df.head()

        age  household_size  distance_from_assigned_polling_booth_km
0  0.315125        0.271142                                -0.796296
1 -1.101169        0.271142                                -1.228948
2  1.141297        0.271142                                -0.460991
3  0.492162       -0.324775                                 0.382681
4  1.259322        0.867059                                 2.545942

In [63]:
df['gender']=df1['gender'].values

In [64]:
df.head()

        age  household_size  distance_from_assigned_polling_booth_km  gender
0  0.315125        0.271142                                -0.796296       1
1 -1.101169        0.271142                                -1.228948       1
2  1.141297        0.271142                                -0.460991       0
3  0.492162       -0.324775                                 0.382681       0
4  1.259322        0.867059                                 2.545942       1

In [65]:
df['voted_status']=df1['voted_status']

In [66]:
df.head()

,age,household_size,distance_from_assigned_polling_booth_km,gender,voted_status
0,0.315125,0.271142,-0.796296,1,1
1,-1.101169,0.271142,-1.228948,1,1
2,1.141297,0.271142,-0.460991,0,1
3,0.492162,-0.324775,0.382681,0,1
4,1.259322,0.867059,2.545942,1,0

In [81]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
X = df.drop('voted_status', axis=1)
y = df['voted_status']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

accuracy_score(y_test, y_pred)

0.89

In [148]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [113]:
dt=DecisionTreeClassifier(criterion='gini',splitter='random')

In [114]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(splitter='random')

In [115]:
y_pred1=dt.predict(X_test)

In [116]:
accuracy_score(y_pred1,y_test)

0.86

In [119]:
from sklearn.model_selection import cross_val_score

In [118]:
import optuna

In [124]:
def objective(trial):
    criterion=trial.suggest_categorical('criterion',['gini','entropy','log_loss'])
    splitter=trial.suggest_categorical('splitter',['best','random'])
    max_depth=trial.suggest_int('max_depth',1,10)
    min_samples_split=trial.suggest_int('min_samples_split',2,20)
    min_samples_leaf=trial.suggest_int('min_samples_leaf',1,10)
    dtc=DecisionTreeClassifier(criterion=criterion,splitter=splitter,max_depth=max_depth,min_samples_split=min_samples_split,min_samples_leaf=min_samples_leaf)
    score=cross_val_score(dtc,X_train,y_train,cv=3,scoring='accuracy').mean()
    return score

In [125]:
study=optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=100)

[I 2026-09-06 11:37:51,551] A new study created in memory with name: no-name-c5aeffd7-a0b1-455f-b277-59af0e70795c
[I 2026-09-06 11:37:51,573] Trial 0 finished with value: 0.8871953829035375 and parameters: {'criterion': 'entropy', 'splitter': 'random', 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.8871953829035375.
[I 2026-09-06 11:37:51,608] Trial 1 finished with value: 0.8942995488059866 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 9, 'min_samples_split': 16, 'min_samples_leaf': 3}. Best is trial 1 with value: 0.8942995488059866.
[I 2026-09-06 11:37:51,640] Trial 2 finished with value: 0.880011738380837 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.8942995488059866.
[I 2026-09-06 11:37:51,670] Trial 3 finished with value: 0.8101011212599195 and parameters: {'criterion': 'gini', 'splitter': 'random', 'max_depth': 3, 'min_samples_split': 12, 'min_samples_leaf': 3}. Best is trial 1 with value: 0.8942995488059866.
[I 2026-09-06 11:37:51,692] Trial 4 finished with value: 0.7257192815132729 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 1, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 1 with value: 0.8942995488059866.
[I 2026-09-06 11:37:51,708] Trial 5 finished with value: 0.865711700475649 and parameters: {'criterion': 'entropy', 'splitter': 'random', 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 5}. Best is trial 1 with value: 0.8942995488059866.
[I 2026-09-06 11:37:51,742] Trial 6 finished with value: 0.8971240966949122 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 8}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:51,758] Trial 7 finished with value: 0.8843096976144187 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:51,799] Trial 8 finished with value: 0.8700707971094236 and parameters: {'criterion': 'log_loss', 'splitter': 'random', 'max_depth': 5, 'min_samples_split': 18, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:51,823] Trial 9 finished with value: 0.8071970947507427 and parameters: {'criterion': 'gini', 'splitter': 'random', 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 7}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:51,869] Trial 10 finished with value: 0.8900321582725016 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:51,900] Trial 11 finished with value: 0.8900260445324824 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 20, 'min_samples_leaf': 1}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:51,932] Trial 12 finished with value: 0.8942995488059866 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 16, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:51,961] Trial 13 finished with value: 0.7242947800887715 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 1, 'min_samples_split': 16, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:51,993] Trial 14 finished with value: 0.8885893156279422 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 10, 'min_samples_split': 20, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,023] Trial 15 finished with value: 0.8757260066272942 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,058] Trial 16 finished with value: 0.880011738380837 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 3, 'min_samples_split': 14, 'min_samples_leaf': 8}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,074] Trial 17 finished with value: 0.8757260066272942 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 18, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,118] Trial 18 finished with value: 0.8957301639705073 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 8, 'min_samples_split': 18, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,142] Trial 19 finished with value: 0.8357543743809838 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 2, 'min_samples_split': 20, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,180] Trial 20 finished with value: 0.8957362777105266 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 18, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,219] Trial 21 finished with value: 0.8957362777105266 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 18, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,242] Trial 22 finished with value: 0.888619884328039 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 18, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,275] Trial 23 finished with value: 0.891456659697003 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 7}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,318] Trial 24 finished with value: 0.8843280388344766 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,348] Trial 25 finished with value: 0.8800178521208565 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,383] Trial 26 finished with value: 0.834244280596212 and parameters: {'criterion': 'log_loss', 'splitter': 'random', 'max_depth': 4, 'min_samples_split': 19, 'min_samples_leaf': 8}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,416] Trial 27 finished with value: 0.8957362777105266 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 15, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,451] Trial 28 finished with value: 0.887189269163518 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 17, 'min_samples_leaf': 7}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,485] Trial 29 finished with value: 0.845805362972745 and parameters: {'criterion': 'gini', 'splitter': 'random', 'max_depth': 8, 'min_samples_split': 11, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,510] Trial 30 finished with value: 0.8814484672853772 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.8971240966949122.

[I 2026-09-06 11:37:52,540] Trial 31 finished with value: 0.8943056625460059 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,575] Trial 32 finished with value: 0.8928872748615237 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 16, 'min_samples_leaf': 1}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,608] Trial 33 finished with value: 0.8928872748615237 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 19, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,642] Trial 34 finished with value: 0.8828974236699558 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 4, 'min_samples_split': 15, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,680] Trial 35 finished with value: 0.888619884328039 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 17, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,709] Trial 36 finished with value: 0.8357543743809838 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 2, 'min_samples_split': 11, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,744] Trial 37 finished with value: 0.8057359108861255 and parameters: {'criterion': 'gini', 'splitter': 'random', 'max_depth': 3, 'min_samples_split': 19, 'min_samples_leaf': 1}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,779] Trial 38 finished with value: 0.8928811611215045 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,809] Trial 39 finished with value: 0.8914138635168678 and parameters: {'criterion': 'gini', 'splitter': 'random', 'max_depth': 6, 'min_samples_split': 13, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,842] Trial 40 finished with value: 0.8928811611215045 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 8, 'min_samples_split': 17, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,873] Trial 41 finished with value: 0.8957301639705073 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 8, 'min_samples_split': 18, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,907] Trial 42 finished with value: 0.8928811611215045 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 10, 'min_samples_split': 19, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,956] Trial 43 finished with value: 0.888619884328039 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 18, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:52,982] Trial 44 finished with value: 0.891456659697003 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 9, 'min_samples_split': 19, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,007] Trial 45 finished with value: 0.8957301639705073 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 17, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,040] Trial 46 finished with value: 0.8771505080517956 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,089] Trial 47 finished with value: 0.8828974236699558 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 4, 'min_samples_split': 16, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,109] Trial 48 finished with value: 0.8314441876673636 and parameters: {'criterion': 'log_loss', 'splitter': 'random', 'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 7}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,141] Trial 49 finished with value: 0.8843096976144187 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 8, 'min_samples_split': 18, 'min_samples_leaf': 1}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,189] Trial 50 finished with value: 0.8928811611215045 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 13, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,222] Trial 51 finished with value: 0.8957301639705073 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 8, 'min_samples_split': 18, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,253] Trial 52 finished with value: 0.8957301639705073 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 9, 'min_samples_split': 16, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,275] Trial 53 finished with value: 0.8914505459569838 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 19, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,313] Trial 54 finished with value: 0.8928811611215045 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 8, 'min_samples_split': 20, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,349] Trial 55 finished with value: 0.8942995488059866 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,379] Trial 56 finished with value: 0.8957362777105266 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,411] Trial 57 finished with value: 0.8843096976144187 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,445] Trial 58 finished with value: 0.888619884328039 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 16, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,477] Trial 59 finished with value: 0.8928811611215045 and parameters: {'criterion': 'log_loss', 'splitter': 'random', 'max_depth': 6, 'min_samples_split': 19, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,507] Trial 60 finished with value: 0.8800178521208565 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 15, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,540] Trial 61 finished with value: 0.8957301639705073 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 18, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.

[I 2026-09-06 11:37:53,579] Trial 62 finished with value: 0.8957362777105266 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,612] Trial 63 finished with value: 0.8943056625460059 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,643] Trial 64 finished with value: 0.8957362777105266 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 18, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,673] Trial 65 finished with value: 0.8928872748615237 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 20, 'min_samples_leaf': 8}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,712] Trial 66 finished with value: 0.887189269163518 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 17, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,745] Trial 67 finished with value: 0.8943056625460059 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 13, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,773] Trial 68 finished with value: 0.8957362777105266 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 16, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,817] Trial 69 finished with value: 0.8828974236699558 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 4, 'min_samples_split': 19, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,849] Trial 70 finished with value: 0.8771566217918149 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 14, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,883] Trial 71 finished with value: 0.8957362777105266 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 16, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,914] Trial 72 finished with value: 0.8928811611215045 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,947] Trial 73 finished with value: 0.8957362777105266 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 16, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:53,978] Trial 74 finished with value: 0.8957362777105266 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,012] Trial 75 finished with value: 0.887189269163518 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 18, 'min_samples_leaf': 7}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,043] Trial 76 finished with value: 0.8871525867234021 and parameters: {'criterion': 'log_loss', 'splitter': 'random', 'max_depth': 7, 'min_samples_split': 17, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,085] Trial 77 finished with value: 0.888619884328039 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 15, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,118] Trial 78 finished with value: 0.8928872748615237 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 19, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,149] Trial 79 finished with value: 0.822933861560471 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 2, 'min_samples_split': 20, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,181] Trial 80 finished with value: 0.7242947800887715 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 1, 'min_samples_split': 16, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,215] Trial 81 finished with value: 0.8957362777105266 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 16, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,247] Trial 82 finished with value: 0.8957362777105266 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,282] Trial 83 finished with value: 0.8928811611215045 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 18, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,306] Trial 84 finished with value: 0.888619884328039 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 17, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,340] Trial 85 finished with value: 0.8957362777105266 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 18, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,378] Trial 86 finished with value: 0.8943117762860252 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 16, 'min_samples_leaf': 8}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,407] Trial 87 finished with value: 0.8871403592433635 and parameters: {'criterion': 'log_loss', 'splitter': 'random', 'max_depth': 6, 'min_samples_split': 15, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,440] Trial 88 finished with value: 0.8857586539989973 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 19, 'min_samples_leaf': 1}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,473] Trial 89 finished with value: 0.8814484672853772 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,507] Trial 90 finished with value: 0.8943056625460059 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 14, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,540] Trial 91 finished with value: 0.8957362777105266 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 16, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,573] Trial 92 finished with value: 0.8957362777105266 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 16, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,606] Trial 93 finished with value: 0.8943056625460059 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 18, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.8971240966949122.

[I 2026-09-06 11:37:54,640] Trial 94 finished with value: 0.888619884328039 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 17, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,673] Trial 95 finished with value: 0.8957301639705073 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 16, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,707] Trial 96 finished with value: 0.8943056625460059 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 15, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,740] Trial 97 finished with value: 0.8928811611215045 and parameters: {'criterion': 'entropy', 'splitter': 'best', 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,773] Trial 98 finished with value: 0.888619884328039 and parameters: {'criterion': 'log_loss', 'splitter': 'best', 'max_depth': 5, 'min_samples_split': 18, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.8971240966949122.
[I 2026-09-06 11:37:54,822] Trial 99 finished with value: 0.8785811232163164 and parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.8971240966949122.

In [126]:
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'criterion': 'gini', 'splitter': 'best', 'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 8}
Best trial accuracy: 0.8971240966949122

In [127]:
clf=DecisionTreeClassifier(criterion='gini',splitter='best',max_depth=4,min_samples_split=20,min_samples_leaf=8)

In [128]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=4, min_samples_leaf=8, min_samples_split=20)

In [133]:
ypred2=clf.predict(X_test)

In [135]:
accuracy_score(ypred2,y_test)

0.88

In [136]:
clf.feature_importances_

array([0.42910014, 0.        , 0.55872166, 0.0121782 ])

In [138]:
def objective(trial):
    criterion=trial.suggest_categorical('criterion',['gini','entropy','log_loss'])
    max_depth=trial.suggest_int('max_depth',1,10)
    min_samples_split=trial.suggest_int('min_samples_split',2,20)
    min_samples_leaf=trial.suggest_int('min_samples_leaf',1,10)
    n_estimators=trial.suggest_int('n_estimators',50,500)
    bootstrap=trial.suggest_categorical('bootstrap',[True,False])
    oob_score=trial.suggest_categorical('oob_score',[True,False])

    if oob_score and not bootstrap:
        oob_score=False

    rfc=RandomForestClassifier(
        criterion=criterion,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        n_estimators=n_estimators,
        bootstrap=bootstrap,
        oob_score=oob_score,
        n_jobs=-1
    )

    score=cross_val_score(rfc,X_train,y_train,cv=3,scoring='accuracy').mean()
    return score

In [142]:
study=optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=100)

[I 2026-09-06 11:47:41,929] A new study created in memory with name: no-name-0734383d-5613-4e21-b093-bcf2043c2aa4
[I 2026-09-06 11:47:42,324] Trial 0 finished with value: 0.8971240966949122 and parameters: {'criterion': 'gini', 'max_depth': 3, 'min_samples_split': 14, 'min_samples_leaf': 8, 'n_estimators': 60, 'bootstrap': False, 'oob_score': True}. Best is trial 0 with value: 0.8971240966949122.
[I 2026-09-06 11:47:43,370] Trial 1 finished with value: 0.8157135345976547 and parameters: {'criterion': 'entropy', 'max_depth': 1, 'min_samples_split': 4, 'min_samples_leaf': 6, 'n_estimators': 164, 'bootstrap': True, 'oob_score': False}. Best is trial 0 with value: 0.8971240966949122.
[I 2026-09-06 11:47:44,683] Trial 2 finished with value: 0.8985669393394714 and parameters: {'criterion': 'entropy', 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 3, 'n_estimators': 274, 'bootstrap': False, 'oob_score': False}. Best is trial 2 with value: 0.8985669393394714.
[I 2026-09-06 11:47:45,886] Trial 3 finished with value: 0.9028587848330337 and parameters: {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 12, 'min_samples_leaf': 9, 'n_estimators': 195, 'bootstrap': True, 'oob_score': False}. Best is trial 3 with value: 0.9028587848330337.
[I 2026-09-06 11:47:47,372] Trial 4 finished with value: 0.9100118606556374 and parameters: {'criterion': 'log_loss', 'max_depth': 7, 'min_samples_split': 14, 'min_samples_leaf': 8, 'n_estimators': 320, 'bootstrap': False, 'oob_score': True}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:47:47,931] Trial 5 finished with value: 0.8913955222968099 and parameters: {'criterion': 'log_loss', 'max_depth': 2, 'min_samples_split': 10, 'min_samples_leaf': 9, 'n_estimators': 70, 'bootstrap': True, 'oob_score': True}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:47:49,567] Trial 6 finished with value: 0.8085849137351283 and parameters: {'criterion': 'gini', 'max_depth': 1, 'min_samples_split': 20, 'min_samples_leaf': 1, 'n_estimators': 281, 'bootstrap': True, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:47:51,688] Trial 7 finished with value: 0.8971179829548929 and parameters: {'criterion': 'entropy', 'max_depth': 3, 'min_samples_split': 12, 'min_samples_leaf': 1, 'n_estimators': 473, 'bootstrap': False, 'oob_score': True}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:47:52,783] Trial 8 finished with value: 0.9085629042710588 and parameters: {'criterion': 'entropy', 'max_depth': 3, 'min_samples_split': 16, 'min_samples_leaf': 7, 'n_estimators': 163, 'bootstrap': True, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:47:55,688] Trial 9 finished with value: 0.9042893999975545 and parameters: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 16, 'min_samples_leaf': 1, 'n_estimators': 485, 'bootstrap': True, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:47:57,377] Trial 10 finished with value: 0.9028648985730531 and parameters: {'criterion': 'log_loss', 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_estimators': 349, 'bootstrap': False, 'oob_score': True}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:47:59,061] Trial 11 finished with value: 0.9042893999975545 and parameters: {'criterion': 'log_loss', 'max_depth': 7, 'min_samples_split': 18, 'min_samples_leaf': 7, 'n_estimators': 369, 'bootstrap': False, 'oob_score': True}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:00,231] Trial 12 finished with value: 0.905713901422056 and parameters: {'criterion': 'log_loss', 'max_depth': 8, 'min_samples_split': 16, 'min_samples_leaf': 10, 'n_estimators': 159, 'bootstrap': True, 'oob_score': True}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:01,381] Trial 13 finished with value: 0.8999975545039923 and parameters: {'criterion': 'entropy', 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 5, 'n_estimators': 244, 'bootstrap': False, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:03,698] Trial 14 finished with value: 0.9085812454911167 and parameters: {'criterion': 'log_loss', 'max_depth': 8, 'min_samples_split': 15, 'min_samples_leaf': 7, 'n_estimators': 387, 'bootstrap': True, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:05,553] Trial 15 finished with value: 0.9042955137375738 and parameters: {'criterion': 'log_loss', 'max_depth': 8, 'min_samples_split': 13, 'min_samples_leaf': 4, 'n_estimators': 397, 'bootstrap': False, 'oob_score': True}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:08,454] Trial 16 finished with value: 0.9042955137375738 and parameters: {'criterion': 'log_loss', 'max_depth': 8, 'min_samples_split': 20, 'min_samples_leaf': 8, 'n_estimators': 423, 'bootstrap': True, 'oob_score': True}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:09,992] Trial 17 finished with value: 0.9100118606556374 and parameters: {'criterion': 'log_loss', 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 10, 'n_estimators': 321, 'bootstrap': False, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:11,546] Trial 18 finished with value: 0.905713901422056 and parameters: {'criterion': 'log_loss', 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 10, 'n_estimators': 332, 'bootstrap': False, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:13,001] Trial 19 finished with value: 0.907150630326596 and parameters: {'criterion': 'log_loss', 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 9, 'n_estimators': 307, 'bootstrap': False, 'oob_score': True}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:14,103] Trial 20 finished with value: 0.9100118606556374 and parameters: {'criterion': 'log_loss', 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 10, 'n_estimators': 230, 'bootstrap': False, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:15,162] Trial 21 finished with value: 0.9085873592311361 and parameters: {'criterion': 'log_loss', 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 10, 'n_estimators': 217, 'bootstrap': False, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:16,740] Trial 22 finished with value: 0.9042893999975545 and parameters: {'criterion': 'log_loss', 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 8, 'n_estimators': 311, 'bootstrap': False, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:17,905] Trial 23 finished with value: 0.9100057469156182 and parameters: {'criterion': 'log_loss', 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 9, 'n_estimators': 233, 'bootstrap': False, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:19,935] Trial 24 finished with value: 0.9100118606556374 and parameters: {'criterion': 'log_loss', 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 10, 'n_estimators': 431, 'bootstrap': False, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:21,289] Trial 25 finished with value: 0.9085812454911167 and parameters: {'criterion': 'log_loss', 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 8, 'n_estimators': 273, 'bootstrap': False, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:21,918] Trial 26 finished with value: 0.9057200151620752 and parameters: {'criterion': 'log_loss', 'max_depth': 9, 'min_samples_split': 18, 'min_samples_leaf': 9, 'n_estimators': 121, 'bootstrap': False, 'oob_score': True}. Best is trial 4 with value: 0.9100118606556374.

[I 2026-09-06 11:48:23,451] Trial 27 finished with value: 0.9085812454911167 and parameters: {'criterion': 'log_loss', 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 10, 'n_estimators': 318, 'bootstrap': False, 'oob_score': False}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:24,742] Trial 28 finished with value: 0.9099935194355795 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 6, 'n_estimators': 254, 'bootstrap': False, 'oob_score': True}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:25,824] Trial 29 finished with value: 0.9085812454911167 and parameters: {'criterion': 'log_loss', 'max_depth': 5, 'min_samples_split': 14, 'min_samples_leaf': 8, 'n_estimators': 201, 'bootstrap': False, 'oob_score': True}. Best is trial 4 with value: 0.9100118606556374.
[I 2026-09-06 11:48:27,473] Trial 30 finished with value: 0.9114241346001003 and parameters: {'criterion': 'gini', 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 9, 'n_estimators': 362, 'bootstrap': False, 'oob_score': False}. Best is trial 30 with value: 0.9114241346001003.
[I 2026-09-06 11:48:29,062] Trial 31 finished with value: 0.9142792511891225 and parameters: {'criterion': 'gini', 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 9, 'n_estimators': 341, 'bootstrap': False, 'oob_score': False}. Best is trial 31 with value: 0.9142792511891225.
[I 2026-09-06 11:48:30,725] Trial 32 finished with value: 0.908569018011078 and parameters: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 8, 'n_estimators': 351, 'bootstrap': False, 'oob_score': False}. Best is trial 31 with value: 0.9142792511891225.
[I 2026-09-06 11:48:32,798] Trial 33 finished with value: 0.9171343677781446 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 9, 'n_estimators': 427, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:48:35,352] Trial 34 finished with value: 0.9142853649291417 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 7, 'n_estimators': 455, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:48:37,559] Trial 35 finished with value: 0.9071384028465573 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_estimators': 439, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:48:39,760] Trial 36 finished with value: 0.9085629042710588 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 7, 'n_estimators': 467, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:48:42,419] Trial 37 finished with value: 0.9100118606556374 and parameters: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 9, 'n_estimators': 500, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:48:44,409] Trial 38 finished with value: 0.9128608635046404 and parameters: {'criterion': 'gini', 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 9, 'n_estimators': 405, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:48:46,247] Trial 39 finished with value: 0.9142792511891225 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 7, 'n_estimators': 404, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:48:48,339] Trial 40 finished with value: 0.9071445165865768 and parameters: {'criterion': 'gini', 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 5, 'n_estimators': 458, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:48:50,208] Trial 41 finished with value: 0.9099935194355795 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_estimators': 403, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:48:52,107] Trial 42 finished with value: 0.9114302483401197 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 7, 'n_estimators': 411, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:48:53,887] Trial 43 finished with value: 0.9128608635046404 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 7, 'n_estimators': 380, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:48:55,916] Trial 44 finished with value: 0.9099996331755987 and parameters: {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 8, 'n_estimators': 449, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:48:58,458] Trial 45 finished with value: 0.9014403971485517 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 9, 'n_estimators': 415, 'bootstrap': True, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:02,965] Trial 46 finished with value: 0.9042893999975545 and parameters: {'criterion': 'gini', 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 2, 'n_estimators': 478, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:05,242] Trial 47 finished with value: 0.9028587848330337 and parameters: {'criterion': 'entropy', 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_estimators': 373, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:08,549] Trial 48 finished with value: 0.9042893999975545 and parameters: {'criterion': 'gini', 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 4, 'n_estimators': 438, 'bootstrap': True, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:10,537] Trial 49 finished with value: 0.9071384028465573 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 7, 'n_estimators': 340, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:12,707] Trial 50 finished with value: 0.9142792511891225 and parameters: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 9, 'n_estimators': 399, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:14,848] Trial 51 finished with value: 0.9100057469156182 and parameters: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 9, 'n_estimators': 386, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:17,364] Trial 52 finished with value: 0.9114302483401197 and parameters: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 9, 'n_estimators': 399, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:19,664] Trial 53 finished with value: 0.9128608635046404 and parameters: {'criterion': 'gini', 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 8, 'n_estimators': 454, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:21,902] Trial 54 finished with value: 0.9071506303265959 and parameters: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 8, 'n_estimators': 423, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.

[I 2026-09-06 11:49:24,046] Trial 55 finished with value: 0.9071445165865768 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 9, 'n_estimators': 357, 'bootstrap': True, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:26,637] Trial 56 finished with value: 0.7743112871868236 and parameters: {'criterion': 'gini', 'max_depth': 1, 'min_samples_split': 4, 'min_samples_leaf': 10, 'n_estimators': 488, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:28,654] Trial 57 finished with value: 0.9114241346001003 and parameters: {'criterion': 'gini', 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 7, 'n_estimators': 393, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:30,099] Trial 58 finished with value: 0.912854749764621 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 8, 'n_estimators': 291, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:32,059] Trial 59 finished with value: 0.9085812454911167 and parameters: {'criterion': 'entropy', 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 9, 'n_estimators': 416, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:34,739] Trial 60 finished with value: 0.9028526710930146 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 5, 'n_estimators': 441, 'bootstrap': True, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:36,524] Trial 61 finished with value: 0.9099996331755987 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 7, 'n_estimators': 381, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:38,464] Trial 62 finished with value: 0.9142853649291417 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 7, 'n_estimators': 372, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:40,184] Trial 63 finished with value: 0.9128486360246018 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 8, 'n_estimators': 336, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:41,887] Trial 64 finished with value: 0.9099935194355795 and parameters: {'criterion': 'gini', 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 6, 'n_estimators': 362, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:43,859] Trial 65 finished with value: 0.909999633175599 and parameters: {'criterion': 'gini', 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 10, 'n_estimators': 426, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:46,286] Trial 66 finished with value: 0.9114241346001003 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 6, 'n_estimators': 464, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:47,986] Trial 67 finished with value: 0.9114302483401197 and parameters: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 8, 'n_estimators': 345, 'bootstrap': False, 'oob_score': True}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:50,050] Trial 68 finished with value: 0.9042832862575353 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 4, 'n_estimators': 406, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:51,890] Trial 69 finished with value: 0.912854749764621 and parameters: {'criterion': 'gini', 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 9, 'n_estimators': 328, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:53,916] Trial 70 finished with value: 0.9057200151620752 and parameters: {'criterion': 'entropy', 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 7, 'n_estimators': 370, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:55,728] Trial 71 finished with value: 0.908569018011078 and parameters: {'criterion': 'gini', 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 7, 'n_estimators': 379, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:57,652] Trial 72 finished with value: 0.9085629042710588 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 7, 'n_estimators': 390, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:49:59,678] Trial 73 finished with value: 0.9142792511891225 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 7, 'n_estimators': 431, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:00,171] Trial 74 finished with value: 0.9128608635046404 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 10, 'n_estimators': 75, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:02,181] Trial 75 finished with value: 0.9142792511891225 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 8, 'n_estimators': 433, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:04,271] Trial 76 finished with value: 0.9142853649291417 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 7, 'n_estimators': 448, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:06,447] Trial 77 finished with value: 0.909999633175599 and parameters: {'criterion': 'gini', 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 6, 'n_estimators': 473, 'bootstrap': False, 'oob_score': True}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:08,698] Trial 78 finished with value: 0.9128486360246016 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 7, 'n_estimators': 493, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:11,441] Trial 79 finished with value: 0.9028587848330337 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 12, 'min_samples_leaf': 5, 'n_estimators': 457, 'bootstrap': True, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:12,885] Trial 80 finished with value: 0.9142792511891225 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 15, 'min_samples_leaf': 7, 'n_estimators': 302, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:14,967] Trial 81 finished with value: 0.9100057469156182 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 8, 'n_estimators': 445, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:17,064] Trial 82 finished with value: 0.911418020860081 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 8, 'n_estimators': 431, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.

[I 2026-09-06 11:50:19,392] Trial 83 finished with value: 0.9114241346001002 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 8, 'n_estimators': 422, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:21,494] Trial 84 finished with value: 0.912854749764621 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 7, 'n_estimators': 432, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:23,703] Trial 85 finished with value: 0.907132289106538 and parameters: {'criterion': 'gini', 'max_depth': 9, 'min_samples_split': 13, 'min_samples_leaf': 6, 'n_estimators': 478, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:25,801] Trial 86 finished with value: 0.909999633175599 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 7, 'n_estimators': 451, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:27,722] Trial 87 finished with value: 0.9071384028465573 and parameters: {'criterion': 'gini', 'max_depth': 6, 'min_samples_split': 11, 'min_samples_leaf': 8, 'n_estimators': 400, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:29,712] Trial 88 finished with value: 0.9071506303265959 and parameters: {'criterion': 'entropy', 'max_depth': 8, 'min_samples_split': 11, 'min_samples_leaf': 9, 'n_estimators': 412, 'bootstrap': False, 'oob_score': True}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:31,803] Trial 89 finished with value: 0.9142792511891225 and parameters: {'criterion': 'gini', 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 7, 'n_estimators': 466, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:33,516] Trial 90 finished with value: 0.9099935194355795 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 6, 'n_estimators': 365, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:34,948] Trial 91 finished with value: 0.9071445165865767 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 17, 'min_samples_leaf': 7, 'n_estimators': 301, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:36,263] Trial 92 finished with value: 0.909999633175599 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 18, 'min_samples_leaf': 7, 'n_estimators': 261, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:37,612] Trial 93 finished with value: 0.9142792511891225 and parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 15, 'min_samples_leaf': 8, 'n_estimators': 278, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:39,068] Trial 94 finished with value: 0.9142853649291417 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 7, 'n_estimators': 314, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:41,146] Trial 95 finished with value: 0.9142792511891225 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 9, 'n_estimators': 439, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:43,565] Trial 96 finished with value: 0.9057200151620753 and parameters: {'criterion': 'gini', 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 6, 'n_estimators': 415, 'bootstrap': True, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:45,197] Trial 97 finished with value: 0.9128486360246018 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 20, 'min_samples_leaf': 8, 'n_estimators': 346, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:47,094] Trial 98 finished with value: 0.9142792511891225 and parameters: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 7, 'n_estimators': 392, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.
[I 2026-09-06 11:50:48,720] Trial 99 finished with value: 0.909999633175599 and parameters: {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 19, 'min_samples_leaf': 8, 'n_estimators': 324, 'bootstrap': False, 'oob_score': False}. Best is trial 33 with value: 0.9171343677781446.

In [143]:
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'criterion': 'gini', 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 9, 'n_estimators': 427, 'bootstrap': False, 'oob_score': False}
Best trial accuracy: 0.9171343677781446

In [150]:
clf2=RandomForestClassifier(criterion='gini',max_depth=8,min_samples_split=5,min_samples_leaf=9,n_estimators=42,bootstrap=False,oob_score=False,random_state=42)
clf2.fit(X_train,y_train)
ypred3=clf2.predict(X_test)
accuracy_score(ypred3,y_test)

0.8866666666666667

In [152]:
X_train

          age  household_size  distance_from_assigned_polling_booth_km  gender
541  0.846236       -2.112525                                 0.177171       1
440  1.554383       -0.920691                                 1.983494       1
482  1.318334        0.271142                                 0.274518       0
422 -1.632279        0.271142                                -0.266297       1
778  0.197101       -1.516608                                 0.609823       1
..        ...             ...                                      ...     ...
106  0.551175        0.867059                                 2.740635       0
270 -0.334009       -0.324775                                -1.272214       0
860 -1.396230       -0.324775                                 0.101457       1
435 -1.573267       -1.516608                                 0.663905       0
102  0.138089        1.462976                                 0.512476       0

[700 rows x 4 columns]

In [153]:
clf2.feature_importances_

array([0.4263867 , 0.00804417, 0.55413129, 0.01143784])

In [154]:
from sklearn.ensemble import BaggingClassifier

def objective(trial):
    n_estimators=trial.suggest_int('n_estimators',50,500)
    max_samples=trial.suggest_float('max_samples',0.5,1.0)
    max_features=trial.suggest_float('max_features',0.5,1.0)
    bootstrap=trial.suggest_categorical('bootstrap',[True,False])
    bootstrap_features=trial.suggest_categorical('bootstrap_features',[True,False])

    bc=BaggingClassifier(
        n_estimators=n_estimators,
        max_samples=max_samples,
        max_features=max_features,
        bootstrap=bootstrap,
        bootstrap_features=bootstrap_features,
        n_jobs=-1
    )

    score=cross_val_score(
        bc,X_train,y_train,cv=3,scoring='accuracy'
    ).mean()

    return score

In [155]:
study=optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=100)

[I 2026-09-06 11:56:42,638] A new study created in memory with name: no-name-0808f853-4c71-49ee-8aed-00318e4149ad
[I 2026-09-06 11:56:59,505] Trial 0 finished with value: 0.8671300881601312 and parameters: {'n_estimators': 477, 'max_samples': 0.8352556615039566, 'max_features': 0.9942003085620132, 'bootstrap': False, 'bootstrap_features': True}. Best is trial 0 with value: 0.8671300881601312.
[I 2026-09-06 11:57:01,156] Trial 1 finished with value: 0.861407627502048 and parameters: {'n_estimators': 196, 'max_samples': 0.7212342417235028, 'max_features': 0.711042036086061, 'bootstrap': True, 'bootstrap_features': True}. Best is trial 0 with value: 0.8671300881601312.
[I 2026-09-06 11:57:03,237] Trial 2 finished with value: 0.8485443185014 and parameters: {'n_estimators': 276, 'max_samples': 0.9051137914900618, 'max_features': 0.5871703546907099, 'bootstrap': True, 'bootstrap_features': True}. Best is trial 0 with value: 0.8671300881601312.
[I 2026-09-06 11:57:04,876] Trial 3 finished with value: 0.8842730151743027 and parameters: {'n_estimators': 331, 'max_samples': 0.6658016404043985, 'max_features': 0.9208582451354002, 'bootstrap': True, 'bootstrap_features': True}. Best is trial 3 with value: 0.8842730151743027.
[I 2026-09-06 11:57:05,730] Trial 4 finished with value: 0.8857158578188621 and parameters: {'n_estimators': 191, 'max_samples': 0.6700387486320281, 'max_features': 0.7661682834891523, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 4 with value: 0.8857158578188621.
[I 2026-09-06 11:57:07,311] Trial 5 finished with value: 0.8871342455033443 and parameters: {'n_estimators': 366, 'max_samples': 0.5821270041854163, 'max_features': 0.957595575137604, 'bootstrap': False, 'bootstrap_features': False}. Best is trial 5 with value: 0.8871342455033443.
[I 2026-09-06 11:57:07,924] Trial 6 finished with value: 0.882842400009782 and parameters: {'n_estimators': 101, 'max_samples': 0.6903368737419406, 'max_features': 0.9356314183962517, 'bootstrap': False, 'bootstrap_features': True}. Best is trial 5 with value: 0.8871342455033443.
[I 2026-09-06 11:57:08,643] Trial 7 finished with value: 0.8900077033124244 and parameters: {'n_estimators': 134, 'max_samples': 0.8169806660171066, 'max_features': 0.7702472516646712, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 7 with value: 0.8900077033124244.
[I 2026-09-06 11:57:11,426] Trial 8 finished with value: 0.8928444786813886 and parameters: {'n_estimators': 384, 'max_samples': 0.7399208647802471, 'max_features': 0.9676809418267875, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 8 with value: 0.8928444786813886.
[I 2026-09-06 11:57:12,745] Trial 9 finished with value: 0.8671117469400732 and parameters: {'n_estimators': 231, 'max_samples': 0.5418808072156274, 'max_features': 0.5324079858831285, 'bootstrap': True, 'bootstrap_features': True}. Best is trial 8 with value: 0.8928444786813886.
[I 2026-09-06 11:57:14,909] Trial 10 finished with value: 0.872852548818214 and parameters: {'n_estimators': 445, 'max_samples': 0.9360039123573556, 'max_features': 0.8496194456638589, 'bootstrap': False, 'bootstrap_features': False}. Best is trial 8 with value: 0.8928444786813886.
[I 2026-09-06 11:57:15,320] Trial 11 finished with value: 0.8428463128033944 and parameters: {'n_estimators': 56, 'max_samples': 0.8044599877577562, 'max_features': 0.7151922996992396, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 8 with value: 0.8928444786813886.
[I 2026-09-06 11:57:16,883] Trial 12 finished with value: 0.8957118227504495 and parameters: {'n_estimators': 400, 'max_samples': 0.7930504716216338, 'max_features': 0.8245954434014162, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 12 with value: 0.8957118227504495.
[I 2026-09-06 11:57:18,444] Trial 13 finished with value: 0.8900077033124244 and parameters: {'n_estimators': 407, 'max_samples': 0.7533274525444917, 'max_features': 0.8521676683410324, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 12 with value: 0.8957118227504495.
[I 2026-09-06 11:57:19,706] Trial 14 finished with value: 0.8914322047369257 and parameters: {'n_estimators': 327, 'max_samples': 0.8636016744020374, 'max_features': 0.8676432130313718, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 12 with value: 0.8957118227504495.
[I 2026-09-06 11:57:21,652] Trial 15 finished with value: 0.8900138170524436 and parameters: {'n_estimators': 496, 'max_samples': 0.9917974643756848, 'max_features': 0.7868198009516438, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 12 with value: 0.8957118227504495.
[I 2026-09-06 11:57:23,703] Trial 16 finished with value: 0.8571280094885245 and parameters: {'n_estimators': 394, 'max_samples': 0.7580100526696654, 'max_features': 0.625311976764698, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 12 with value: 0.8957118227504495.
[I 2026-09-06 11:57:24,897] Trial 17 finished with value: 0.8985669393394714 and parameters: {'n_estimators': 297, 'max_samples': 0.6131762151784692, 'max_features': 0.887397071679787, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 17 with value: 0.8985669393394714.
[I 2026-09-06 11:57:26,095] Trial 18 finished with value: 0.8857158578188621 and parameters: {'n_estimators': 295, 'max_samples': 0.5893800327882613, 'max_features': 0.8950753192565277, 'bootstrap': False, 'bootstrap_features': False}. Best is trial 17 with value: 0.8985669393394714.
[I 2026-09-06 11:57:27,446] Trial 19 finished with value: 0.8985791668195101 and parameters: {'n_estimators': 264, 'max_samples': 0.6092588462007352, 'max_features': 0.8255052706409196, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 19 with value: 0.8985791668195101.
[I 2026-09-06 11:57:28,576] Trial 20 finished with value: 0.8614015137620288 and parameters: {'n_estimators': 249, 'max_samples': 0.6059818506754341, 'max_features': 0.7146772801398491, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 19 with value: 0.8985791668195101.
[I 2026-09-06 11:57:29,771] Trial 21 finished with value: 0.8957118227504494 and parameters: {'n_estimators': 329, 'max_samples': 0.5142423808811583, 'max_features': 0.8479685511734135, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 19 with value: 0.8985791668195101.
[I 2026-09-06 11:57:31,387] Trial 22 finished with value: 0.89570570901043 and parameters: {'n_estimators': 436, 'max_samples': 0.6272879855721312, 'max_features': 0.8133669270974706, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 19 with value: 0.8985791668195101.
[I 2026-09-06 11:57:32,232] Trial 23 finished with value: 0.89570570901043 and parameters: {'n_estimators': 203, 'max_samples': 0.5494385262712571, 'max_features': 0.8141817123054861, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 19 with value: 0.8985791668195101.
[I 2026-09-06 11:57:33,376] Trial 24 finished with value: 0.8971424379149701 and parameters: {'n_estimators': 278, 'max_samples': 0.6457925502536972, 'max_features': 0.8982357515794718, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 19 with value: 0.8985791668195101.
[I 2026-09-06 11:57:34,874] Trial 25 finished with value: 0.892850592421408 and parameters: {'n_estimators': 283, 'max_samples': 0.6347651995968052, 'max_features': 0.8971937578765823, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 19 with value: 0.8985791668195101.
[I 2026-09-06 11:57:35,817] Trial 26 finished with value: 0.8900199307924629 and parameters: {'n_estimators': 156, 'max_samples': 0.6947940163163657, 'max_features': 0.9062911311910646, 'bootstrap': False, 'bootstrap_features': False}. Best is trial 19 with value: 0.8985791668195101.
[I 2026-09-06 11:57:36,967] Trial 27 finished with value: 0.8999914407639729 and parameters: {'n_estimators': 237, 'max_samples': 0.5036190501299553, 'max_features': 0.9944039492940495, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 27 with value: 0.8999914407639729.

[I 2026-09-06 11:57:37,907] Trial 28 finished with value: 0.8985730530794909 and parameters: {'n_estimators': 243, 'max_samples': 0.5010559497367858, 'max_features': 0.9935990117341003, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 27 with value: 0.8999914407639729.
[I 2026-09-06 11:57:38,554] Trial 29 finished with value: 0.8871342455033443 and parameters: {'n_estimators': 150, 'max_samples': 0.5036990015788387, 'max_features': 0.9993521331850216, 'bootstrap': False, 'bootstrap_features': True}. Best is trial 27 with value: 0.8999914407639729.
[I 2026-09-06 11:57:39,459] Trial 30 finished with value: 0.8985852805595295 and parameters: {'n_estimators': 234, 'max_samples': 0.5641279028837185, 'max_features': 0.9758805890739546, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 27 with value: 0.8999914407639729.
[I 2026-09-06 11:57:40,524] Trial 31 finished with value: 0.8971363241749507 and parameters: {'n_estimators': 239, 'max_samples': 0.5549426129123769, 'max_features': 0.9776091952450476, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 27 with value: 0.8999914407639729.
[I 2026-09-06 11:57:41,370] Trial 32 finished with value: 0.899991440763973 and parameters: {'n_estimators': 206, 'max_samples': 0.5255871222209684, 'max_features': 0.9507934386776439, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 32 with value: 0.899991440763973.
[I 2026-09-06 11:57:42,329] Trial 33 finished with value: 0.8971424379149701 and parameters: {'n_estimators': 208, 'max_samples': 0.5719780584759809, 'max_features': 0.9403208199258744, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 32 with value: 0.899991440763973.
[I 2026-09-06 11:57:43,149] Trial 34 finished with value: 0.8742648227626768 and parameters: {'n_estimators': 180, 'max_samples': 0.5312425677818403, 'max_features': 0.9541312915175064, 'bootstrap': True, 'bootstrap_features': True}. Best is trial 32 with value: 0.899991440763973.
[I 2026-09-06 11:57:44,025] Trial 35 finished with value: 0.8628321289265495 and parameters: {'n_estimators': 219, 'max_samples': 0.5715557991681752, 'max_features': 0.6761032417663917, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 32 with value: 0.899991440763973.
[I 2026-09-06 11:57:44,693] Trial 36 finished with value: 0.8857158578188621 and parameters: {'n_estimators': 167, 'max_samples': 0.5330135438772323, 'max_features': 0.9385006599155197, 'bootstrap': True, 'bootstrap_features': True}. Best is trial 32 with value: 0.899991440763973.
[I 2026-09-06 11:57:45,593] Trial 37 finished with value: 0.9071445165865768 and parameters: {'n_estimators': 258, 'max_samples': 0.5951582483021767, 'max_features': 0.9773554637798927, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:46,103] Trial 38 finished with value: 0.8957362777105266 and parameters: {'n_estimators': 120, 'max_samples': 0.655511444492917, 'max_features': 0.972900536825816, 'bootstrap': False, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:47,222] Trial 39 finished with value: 0.8857219715588814 and parameters: {'n_estimators': 317, 'max_samples': 0.5818451275173077, 'max_features': 0.9210950600795282, 'bootstrap': True, 'bootstrap_features': True}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:48,431] Trial 40 finished with value: 0.8985669393394714 and parameters: {'n_estimators': 351, 'max_samples': 0.5275250022576482, 'max_features': 0.9814336445152206, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:49,366] Trial 41 finished with value: 0.8957179364904686 and parameters: {'n_estimators': 253, 'max_samples': 0.6062883403491517, 'max_features': 0.9530488112614578, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:50,624] Trial 42 finished with value: 0.8999975545039923 and parameters: {'n_estimators': 258, 'max_samples': 0.5597444073143959, 'max_features': 0.92200155512716, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:51,530] Trial 43 finished with value: 0.9042893999975545 and parameters: {'n_estimators': 193, 'max_samples': 0.5714835326589874, 'max_features': 0.9253887677705107, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:52,333] Trial 44 finished with value: 0.9014159421884743 and parameters: {'n_estimators': 191, 'max_samples': 0.5474557153595818, 'max_features': 0.9233047260728053, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:53,140] Trial 45 finished with value: 0.9000097819840308 and parameters: {'n_estimators': 186, 'max_samples': 0.5906647653197586, 'max_features': 0.9301571991941289, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:53,860] Trial 46 finished with value: 0.8985730530794909 and parameters: {'n_estimators': 181, 'max_samples': 0.684306244881738, 'max_features': 0.9178495432709848, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:54,291] Trial 47 finished with value: 0.8514238900504995 and parameters: {'n_estimators': 98, 'max_samples': 0.5970717425958021, 'max_features': 0.8723791532915409, 'bootstrap': False, 'bootstrap_features': True}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:55,129] Trial 48 finished with value: 0.9071445165865768 and parameters: {'n_estimators': 190, 'max_samples': 0.5513210573599276, 'max_features': 0.9257367818822829, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:55,765] Trial 49 finished with value: 0.89570570901043 and parameters: {'n_estimators': 129, 'max_samples': 0.6679608316489105, 'max_features': 0.8754338342831399, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:56,480] Trial 50 finished with value: 0.8999975545039923 and parameters: {'n_estimators': 94, 'max_samples': 0.7157176918835446, 'max_features': 0.9239927375944887, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:57:57,898] Trial 51 finished with value: 0.8985791668195101 and parameters: {'n_estimators': 189, 'max_samples': 0.543496982412528, 'max_features': 0.9263493621816167, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:00,184] Trial 52 finished with value: 0.8914322047369257 and parameters: {'n_estimators': 220, 'max_samples': 0.6266957688880508, 'max_features': 0.9586455113560863, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:01,238] Trial 53 finished with value: 0.8928628199014464 and parameters: {'n_estimators': 156, 'max_samples': 0.5853593143870687, 'max_features': 0.9133907297432542, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:02,766] Trial 54 finished with value: 0.9014281696685131 and parameters: {'n_estimators': 262, 'max_samples': 0.5561442722934641, 'max_features': 0.8809901604574157, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:03,492] Trial 55 finished with value: 0.8814362398053385 and parameters: {'n_estimators': 173, 'max_samples': 0.5867037706012553, 'max_features': 0.5030369625363149, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.

[I 2026-09-06 11:58:04,808] Trial 56 finished with value: 0.8971424379149701 and parameters: {'n_estimators': 299, 'max_samples': 0.618429850329961, 'max_features': 0.8592642991528413, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:06,029] Trial 57 finished with value: 0.8971363241749507 and parameters: {'n_estimators': 220, 'max_samples': 0.5470925366387043, 'max_features': 0.8385507098443772, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:06,972] Trial 58 finished with value: 0.8928689336414658 and parameters: {'n_estimators': 195, 'max_samples': 0.6424621739309393, 'max_features': 0.8873014963106278, 'bootstrap': False, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:07,504] Trial 59 finished with value: 0.9014342834085323 and parameters: {'n_estimators': 62, 'max_samples': 0.5675239782334678, 'max_features': 0.794252948673603, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:07,991] Trial 60 finished with value: 0.8942689801058901 and parameters: {'n_estimators': 57, 'max_samples': 0.5699439523927757, 'max_features': 0.783836055069919, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:08,561] Trial 61 finished with value: 0.9042832862575353 and parameters: {'n_estimators': 83, 'max_samples': 0.6006761649423158, 'max_features': 0.7571537244681038, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:09,002] Trial 62 finished with value: 0.8714525023537899 and parameters: {'n_estimators': 81, 'max_samples': 0.5578464421210656, 'max_features': 0.7419201016615815, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:09,421] Trial 63 finished with value: 0.9042893999975545 and parameters: {'n_estimators': 80, 'max_samples': 0.5194899687889397, 'max_features': 0.7509450770286551, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:09,876] Trial 64 finished with value: 0.8700035459692113 and parameters: {'n_estimators': 77, 'max_samples': 0.5169855296760273, 'max_features': 0.742182638828755, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:10,254] Trial 65 finished with value: 0.8556790531039459 and parameters: {'n_estimators': 51, 'max_samples': 0.5985026148193687, 'max_features': 0.6731662661645736, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:10,871] Trial 66 finished with value: 0.8914322047369257 and parameters: {'n_estimators': 112, 'max_samples': 0.8746857093946799, 'max_features': 0.7524107272406633, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:11,281] Trial 67 finished with value: 0.8914322047369257 and parameters: {'n_estimators': 74, 'max_samples': 0.61909694644649, 'max_features': 0.8056399157490044, 'bootstrap': True, 'bootstrap_features': True}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:11,692] Trial 68 finished with value: 0.8914322047369257 and parameters: {'n_estimators': 68, 'max_samples': 0.5167928890833764, 'max_features': 0.6874095175583504, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:12,261] Trial 69 finished with value: 0.8928567061614272 and parameters: {'n_estimators': 143, 'max_samples': 0.5763156626803094, 'max_features': 0.7955578845078964, 'bootstrap': False, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:12,781] Trial 70 finished with value: 0.8971424379149702 and parameters: {'n_estimators': 112, 'max_samples': 0.5359469615466089, 'max_features': 0.770890421466932, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:13,586] Trial 71 finished with value: 0.8685484758446131 and parameters: {'n_estimators': 134, 'max_samples': 0.5542385066208302, 'max_features': 0.7183825061294444, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:14,151] Trial 72 finished with value: 0.9000097819840308 and parameters: {'n_estimators': 88, 'max_samples': 0.5409232953775884, 'max_features': 0.82862136326794, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:15,475] Trial 73 finished with value: 0.8771382805717569 and parameters: {'n_estimators': 275, 'max_samples': 0.5160139984368481, 'max_features': 0.725443889920964, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:15,847] Trial 74 finished with value: 0.8614015137620288 and parameters: {'n_estimators': 64, 'max_samples': 0.5670254925997728, 'max_features': 0.64015009994757, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:16,857] Trial 75 finished with value: 0.8942873213259479 and parameters: {'n_estimators': 269, 'max_samples': 0.9572897710900754, 'max_features': 0.7681742401862937, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:17,527] Trial 76 finished with value: 0.8928444786813886 and parameters: {'n_estimators': 164, 'max_samples': 0.6051673836650198, 'max_features': 0.8839215859663436, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:18,017] Trial 77 finished with value: 0.8985608255994523 and parameters: {'n_estimators': 108, 'max_samples': 0.5491699182592228, 'max_features': 0.9633618226820305, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:19,037] Trial 78 finished with value: 0.8985730530794909 and parameters: {'n_estimators': 286, 'max_samples': 0.6515561249548594, 'max_features': 0.9041506833264105, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:20,096] Trial 79 finished with value: 0.8542728928995024 and parameters: {'n_estimators': 312, 'max_samples': 0.6319918956268699, 'max_features': 0.7029715291289129, 'bootstrap': True, 'bootstrap_features': True}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:21,349] Trial 80 finished with value: 0.9000036682440116 and parameters: {'n_estimators': 360, 'max_samples': 0.575693272829507, 'max_features': 0.9453260862767945, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:22,128] Trial 81 finished with value: 0.8914322047369257 and parameters: {'n_estimators': 211, 'max_samples': 0.5969256615714448, 'max_features': 0.9849438280138256, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:22,877] Trial 82 finished with value: 0.9014220559284937 and parameters: {'n_estimators': 187, 'max_samples': 0.5888521153872871, 'max_features': 0.7540201855522072, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:23,875] Trial 83 finished with value: 0.8785627819962584 and parameters: {'n_estimators': 227, 'max_samples': 0.533235752684183, 'max_features': 0.747446238980503, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.

[I 2026-09-06 11:58:24,819] Trial 84 finished with value: 0.8999975545039923 and parameters: {'n_estimators': 248, 'max_samples': 0.5595731303009737, 'max_features': 0.7555075934048652, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:25,397] Trial 85 finished with value: 0.9042710587774966 and parameters: {'n_estimators': 138, 'max_samples': 0.5012301285292269, 'max_features': 0.7864122093250805, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:25,944] Trial 86 finished with value: 0.8971363241749509 and parameters: {'n_estimators': 127, 'max_samples': 0.5067378332455847, 'max_features': 0.7842388096769064, 'bootstrap': False, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:26,352] Trial 87 finished with value: 0.8942689801058901 and parameters: {'n_estimators': 89, 'max_samples': 0.527611429422559, 'max_features': 0.8081521442851747, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:26,934] Trial 88 finished with value: 0.8700157734492499 and parameters: {'n_estimators': 149, 'max_samples': 0.5812969515344932, 'max_features': 0.7293660632329204, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:27,484] Trial 89 finished with value: 0.9000097819840308 and parameters: {'n_estimators': 120, 'max_samples': 0.5239727566570477, 'max_features': 0.7949541646991524, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:27,997] Trial 90 finished with value: 0.884279128914322 and parameters: {'n_estimators': 103, 'max_samples': 0.613185571558376, 'max_features': 0.7643157607699376, 'bootstrap': True, 'bootstrap_features': True}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:28,764] Trial 91 finished with value: 0.8485504322414194 and parameters: {'n_estimators': 203, 'max_samples': 0.5434014235688424, 'max_features': 0.7368941331565934, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:29,452] Trial 92 finished with value: 0.9042893999975545 and parameters: {'n_estimators': 177, 'max_samples': 0.5013377133783546, 'max_features': 0.9362633524583289, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:30,164] Trial 93 finished with value: 0.9028587848330337 and parameters: {'n_estimators': 169, 'max_samples': 0.5032401329039957, 'max_features': 0.7746131389147592, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:30,865] Trial 94 finished with value: 0.9042832862575351 and parameters: {'n_estimators': 172, 'max_samples': 0.5098702629530064, 'max_features': 0.7738513961400038, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:31,531] Trial 95 finished with value: 0.8914138635168678 and parameters: {'n_estimators': 169, 'max_samples': 0.5054985108601406, 'max_features': 0.7809791960325857, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:32,151] Trial 96 finished with value: 0.8713913649535967 and parameters: {'n_estimators': 160, 'max_samples': 0.5002281919841859, 'max_features': 0.7005828483602669, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:32,851] Trial 97 finished with value: 0.904295513737574 and parameters: {'n_estimators': 176, 'max_samples': 0.5160606992904324, 'max_features': 0.8246127573656294, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:33,407] Trial 98 finished with value: 0.8985730530794909 and parameters: {'n_estimators': 138, 'max_samples': 0.5199531594682073, 'max_features': 0.8161939129392364, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.
[I 2026-09-06 11:58:34,134] Trial 99 finished with value: 0.9028465573529951 and parameters: {'n_estimators': 175, 'max_samples': 0.5326870851104333, 'max_features': 0.8583049704132797, 'bootstrap': True, 'bootstrap_features': False}. Best is trial 37 with value: 0.9071445165865768.

In [156]:
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'n_estimators': 258, 'max_samples': 0.5951582483021767, 'max_features': 0.9773554637798927, 'bootstrap': True, 'bootstrap_features': False}
Best trial accuracy: 0.9071445165865768

In [157]:
bg=BaggingClassifier(**study.best_trial.params,random_state=42)
bg.fit(X_train,y_train)
ypred4=bg.predict(X_test)
accuracy_score(ypred4,y_test)

0.8733333333333333

In [158]:
from sklearn.ensemble import GradientBoostingClassifier

def objective(trial):
    loss=trial.suggest_categorical('loss',['log_loss','exponential'])
    learning_rate=trial.suggest_float('learning_rate',0.01,0.3)
    n_estimators=trial.suggest_int('n_estimators',50,500)
    max_depth=trial.suggest_int('max_depth',1,10)
    min_samples_split=trial.suggest_int('min_samples_split',2,20)
    min_samples_leaf=trial.suggest_int('min_samples_leaf',1,10)

    gbc=GradientBoostingClassifier(
        loss=loss,
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf
    )

    score=cross_val_score(
        gbc,X_train,y_train,cv=3,scoring='accuracy'
    ).mean()

    return score

In [159]:
study1=optuna.create_study(direction='maximize')
study1.optimize(objective,n_trials=100)

[I 2026-09-06 12:01:29,264] A new study created in memory with name: no-name-027084fd-49e9-4e73-91ed-e0474c121f6e
[I 2026-09-06 12:01:29,938] Trial 0 finished with value: 0.8928689336414658 and parameters: {'loss': 'log_loss', 'learning_rate': 0.19242407566668, 'n_estimators': 103, 'max_depth': 5, 'min_samples_split': 13, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.8928689336414658.
[I 2026-09-06 12:01:32,650] Trial 1 finished with value: 0.8871464729833828 and parameters: {'loss': 'exponential', 'learning_rate': 0.07152454770672548, 'n_estimators': 229, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.8928689336414658.
[I 2026-09-06 12:01:36,748] Trial 2 finished with value: 0.888564860667865 and parameters: {'loss': 'exponential', 'learning_rate': 0.12317480040176784, 'n_estimators': 483, 'max_depth': 7, 'min_samples_split': 13, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.8928689336414658.
[I 2026-09-06 12:01:39,255] Trial 3 finished with value: 0.8928567061614272 and parameters: {'loss': 'exponential', 'learning_rate': 0.08770913414432616, 'n_estimators': 244, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.8928689336414658.
[I 2026-09-06 12:01:40,039] Trial 4 finished with value: 0.9000036682440117 and parameters: {'loss': 'log_loss', 'learning_rate': 0.01660512678708987, 'n_estimators': 246, 'max_depth': 2, 'min_samples_split': 15, 'min_samples_leaf': 7}. Best is trial 4 with value: 0.9000036682440117.
[I 2026-09-06 12:01:41,754] Trial 5 finished with value: 0.8914260909969065 and parameters: {'loss': 'log_loss', 'learning_rate': 0.21178586153688542, 'n_estimators': 204, 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 2}. Best is trial 4 with value: 0.9000036682440117.
[I 2026-09-06 12:01:43,133] Trial 6 finished with value: 0.8871464729833828 and parameters: {'loss': 'log_loss', 'learning_rate': 0.1431417783150538, 'n_estimators': 93, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 4 with value: 0.9000036682440117.
[I 2026-09-06 12:01:43,821] Trial 7 finished with value: 0.9085934729711553 and parameters: {'loss': 'log_loss', 'learning_rate': 0.11690932414376755, 'n_estimators': 282, 'max_depth': 1, 'min_samples_split': 18, 'min_samples_leaf': 9}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:01:44,785] Trial 8 finished with value: 0.8828668549698593 and parameters: {'loss': 'exponential', 'learning_rate': 0.22526553526095672, 'n_estimators': 310, 'max_depth': 2, 'min_samples_split': 10, 'min_samples_leaf': 8}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:01:49,909] Trial 9 finished with value: 0.8914260909969065 and parameters: {'loss': 'exponential', 'learning_rate': 0.10421261491986168, 'n_estimators': 482, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:01:51,682] Trial 10 finished with value: 0.8828607412298398 and parameters: {'loss': 'log_loss', 'learning_rate': 0.2909541689323263, 'n_estimators': 353, 'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 10}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:01:52,619] Trial 11 finished with value: 0.9057077876820365 and parameters: {'loss': 'log_loss', 'learning_rate': 0.03174683566010923, 'n_estimators': 359, 'max_depth': 1, 'min_samples_split': 19, 'min_samples_leaf': 10}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:01:53,537] Trial 12 finished with value: 0.9028465573529951 and parameters: {'loss': 'log_loss', 'learning_rate': 0.02441604117964971, 'n_estimators': 362, 'max_depth': 1, 'min_samples_split': 20, 'min_samples_leaf': 10}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:01:54,541] Trial 13 finished with value: 0.9043077412176125 and parameters: {'loss': 'log_loss', 'learning_rate': 0.05164499307589017, 'n_estimators': 405, 'max_depth': 1, 'min_samples_split': 18, 'min_samples_leaf': 9}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:01:55,174] Trial 14 finished with value: 0.8928628199014464 and parameters: {'loss': 'log_loss', 'learning_rate': 0.1507223790854318, 'n_estimators': 159, 'max_depth': 3, 'min_samples_split': 17, 'min_samples_leaf': 9}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:01:56,336] Trial 15 finished with value: 0.8957179364904686 and parameters: {'loss': 'log_loss', 'learning_rate': 0.05641026407034805, 'n_estimators': 304, 'max_depth': 3, 'min_samples_split': 17, 'min_samples_leaf': 6}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:01:57,307] Trial 16 finished with value: 0.8985975080395682 and parameters: {'loss': 'log_loss', 'learning_rate': 0.14783747275457582, 'n_estimators': 400, 'max_depth': 1, 'min_samples_split': 20, 'min_samples_leaf': 9}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:01:58,970] Trial 17 finished with value: 0.8814362398053386 and parameters: {'loss': 'log_loss', 'learning_rate': 0.17881790321566104, 'n_estimators': 295, 'max_depth': 5, 'min_samples_split': 14, 'min_samples_leaf': 10}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:02:00,256] Trial 18 finished with value: 0.8757321203673135 and parameters: {'loss': 'log_loss', 'learning_rate': 0.2592819334742552, 'n_estimators': 427, 'max_depth': 2, 'min_samples_split': 18, 'min_samples_leaf': 8}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:02:01,651] Trial 19 finished with value: 0.8814362398053386 and parameters: {'loss': 'log_loss', 'learning_rate': 0.10583794194474005, 'n_estimators': 350, 'max_depth': 3, 'min_samples_split': 16, 'min_samples_leaf': 8}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:02:03,022] Trial 20 finished with value: 0.8971546653950088 and parameters: {'loss': 'log_loss', 'learning_rate': 0.03832946579286983, 'n_estimators': 287, 'max_depth': 4, 'min_samples_split': 19, 'min_samples_leaf': 5}. Best is trial 7 with value: 0.9085934729711553.
[I 2026-09-06 12:02:04,024] Trial 21 finished with value: 0.9085995867111746 and parameters: {'loss': 'log_loss', 'learning_rate': 0.06112664600275419, 'n_estimators': 416, 'max_depth': 1, 'min_samples_split': 18, 'min_samples_leaf': 9}. Best is trial 21 with value: 0.9085995867111746.
[I 2026-09-06 12:02:05,040] Trial 22 finished with value: 0.9028771260530917 and parameters: {'loss': 'log_loss', 'learning_rate': 0.07682163683992531, 'n_estimators': 427, 'max_depth': 1, 'min_samples_split': 18, 'min_samples_leaf': 9}. Best is trial 21 with value: 0.9085995867111746.
[I 2026-09-06 12:02:06,185] Trial 23 finished with value: 0.8957240502304881 and parameters: {'loss': 'log_loss', 'learning_rate': 0.04743319490564762, 'n_estimators': 377, 'max_depth': 2, 'min_samples_split': 16, 'min_samples_leaf': 10}. Best is trial 21 with value: 0.9085995867111746.
[I 2026-09-06 12:02:07,257] Trial 24 finished with value: 0.9057383563821332 and parameters: {'loss': 'log_loss', 'learning_rate': 0.0929856513674273, 'n_estimators': 449, 'max_depth': 1, 'min_samples_split': 12, 'min_samples_leaf': 8}. Best is trial 21 with value: 0.9085995867111746.
[I 2026-09-06 12:02:08,612] Trial 25 finished with value: 0.8800056246408178 and parameters: {'loss': 'log_loss', 'learning_rate': 0.11925058008131316, 'n_estimators': 454, 'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 7}. Best is trial 21 with value: 0.9085995867111746.
[I 2026-09-06 12:02:10,502] Trial 26 finished with value: 0.8843035838743992 and parameters: {'loss': 'exponential', 'learning_rate': 0.08949733424971479, 'n_estimators': 494, 'max_depth': 3, 'min_samples_split': 12, 'min_samples_leaf': 8}. Best is trial 21 with value: 0.9085995867111746.

[I 2026-09-06 12:02:10,931] Trial 27 finished with value: 0.910024088135676 and parameters: {'loss': 'log_loss', 'learning_rate': 0.1233655082426866, 'n_estimators': 159, 'max_depth': 1, 'min_samples_split': 2, 'min_samples_leaf': 6}. Best is trial 27 with value: 0.910024088135676.
[I 2026-09-06 12:02:11,398] Trial 28 finished with value: 0.8942934350659671 and parameters: {'loss': 'log_loss', 'learning_rate': 0.16751895594048619, 'n_estimators': 158, 'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 27 with value: 0.910024088135676.
[I 2026-09-06 12:02:12,069] Trial 29 finished with value: 0.8971424379149702 and parameters: {'loss': 'log_loss', 'learning_rate': 0.12616476560351358, 'n_estimators': 138, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 6}. Best is trial 27 with value: 0.910024088135676.
[I 2026-09-06 12:02:13,258] Trial 30 finished with value: 0.8857097440788427 and parameters: {'loss': 'log_loss', 'learning_rate': 0.19716293329197787, 'n_estimators': 194, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 7}. Best is trial 27 with value: 0.910024088135676.
[I 2026-09-06 12:02:14,295] Trial 31 finished with value: 0.9000342369441082 and parameters: {'loss': 'log_loss', 'learning_rate': 0.10338463182841302, 'n_estimators': 449, 'max_depth': 1, 'min_samples_split': 12, 'min_samples_leaf': 8}. Best is trial 27 with value: 0.910024088135676.
[I 2026-09-06 12:02:14,505] Trial 32 finished with value: 0.8913894085567905 and parameters: {'loss': 'log_loss', 'learning_rate': 0.06956012552872616, 'n_estimators': 75, 'max_depth': 1, 'min_samples_split': 7, 'min_samples_leaf': 9}. Best is trial 27 with value: 0.910024088135676.
[I 2026-09-06 12:02:15,354] Trial 33 finished with value: 0.8900138170524436 and parameters: {'loss': 'log_loss', 'learning_rate': 0.13005492152120793, 'n_estimators': 267, 'max_depth': 2, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 27 with value: 0.910024088135676.
[I 2026-09-06 12:02:16,176] Trial 34 finished with value: 0.9143037061491998 and parameters: {'loss': 'exponential', 'learning_rate': 0.07043663049927229, 'n_estimators': 334, 'max_depth': 1, 'min_samples_split': 13, 'min_samples_leaf': 7}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:16,421] Trial 35 finished with value: 0.9100118606556374 and parameters: {'loss': 'exponential', 'learning_rate': 0.06776298214576429, 'n_estimators': 53, 'max_depth': 3, 'min_samples_split': 14, 'min_samples_leaf': 6}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:16,970] Trial 36 finished with value: 0.8871525867234021 and parameters: {'loss': 'exponential', 'learning_rate': 0.011094133154014897, 'n_estimators': 62, 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 6}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:17,455] Trial 37 finished with value: 0.8942934350659671 and parameters: {'loss': 'exponential', 'learning_rate': 0.07407341977085868, 'n_estimators': 114, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:19,812] Trial 38 finished with value: 0.8857158578188621 and parameters: {'loss': 'exponential', 'learning_rate': 0.06425028387065279, 'n_estimators': 209, 'max_depth': 10, 'min_samples_split': 13, 'min_samples_leaf': 6}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:20,364] Trial 39 finished with value: 0.9000036682440116 and parameters: {'loss': 'exponential', 'learning_rate': 0.07831643088084536, 'n_estimators': 103, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 1}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:20,573] Trial 40 finished with value: 0.9099874056955602 and parameters: {'loss': 'exponential', 'learning_rate': 0.04339710145477196, 'n_estimators': 54, 'max_depth': 2, 'min_samples_split': 8, 'min_samples_leaf': 7}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:20,755] Trial 41 finished with value: 0.9071261753665188 and parameters: {'loss': 'exponential', 'learning_rate': 0.041067613013323664, 'n_estimators': 52, 'max_depth': 2, 'min_samples_split': 8, 'min_samples_leaf': 7}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:21,752] Trial 42 finished with value: 0.9028710123130724 and parameters: {'loss': 'exponential', 'learning_rate': 0.05922575085368456, 'n_estimators': 326, 'max_depth': 2, 'min_samples_split': 15, 'min_samples_leaf': 7}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:22,302] Trial 43 finished with value: 0.9114363620801389 and parameters: {'loss': 'exponential', 'learning_rate': 0.025533452911700852, 'n_estimators': 126, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:22,687] Trial 44 finished with value: 0.908569018011078 and parameters: {'loss': 'exponential', 'learning_rate': 0.03153745279508095, 'n_estimators': 88, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:23,235] Trial 45 finished with value: 0.9099996331755987 and parameters: {'loss': 'exponential', 'learning_rate': 0.02031381370902846, 'n_estimators': 127, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:24,205] Trial 46 finished with value: 0.8985852805595295 and parameters: {'loss': 'exponential', 'learning_rate': 0.02286708598940583, 'n_estimators': 129, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:25,208] Trial 47 finished with value: 0.8942934350659671 and parameters: {'loss': 'exponential', 'learning_rate': 0.012622599808325655, 'n_estimators': 176, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:26,129] Trial 48 finished with value: 0.9000036682440117 and parameters: {'loss': 'exponential', 'learning_rate': 0.029834766735673673, 'n_estimators': 229, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 6}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:27,260] Trial 49 finished with value: 0.8957179364904686 and parameters: {'loss': 'exponential', 'learning_rate': 0.08462655225930737, 'n_estimators': 137, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:28,487] Trial 50 finished with value: 0.8857097440788427 and parameters: {'loss': 'exponential', 'learning_rate': 0.09897768637506049, 'n_estimators': 81, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 34 with value: 0.9143037061491998.
[I 2026-09-06 12:02:28,850] Trial 51 finished with value: 0.9171588227382218 and parameters: {'loss': 'exponential', 'learning_rate': 0.043700016105113045, 'n_estimators': 109, 'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 7}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:29,333] Trial 52 finished with value: 0.9042832862575353 and parameters: {'loss': 'exponential', 'learning_rate': 0.02130096059235855, 'n_estimators': 114, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 6}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:30,187] Trial 53 finished with value: 0.8928689336414658 and parameters: {'loss': 'exponential', 'learning_rate': 0.050549777855289094, 'n_estimators': 160, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:30,554] Trial 54 finished with value: 0.9157282075737011 and parameters: {'loss': 'exponential', 'learning_rate': 0.03489652420338979, 'n_estimators': 109, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 51 with value: 0.9171588227382218.

[I 2026-09-06 12:02:30,871] Trial 55 finished with value: 0.9142975924091804 and parameters: {'loss': 'exponential', 'learning_rate': 0.03689386847468541, 'n_estimators': 101, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:31,226] Trial 56 finished with value: 0.9128669772446596 and parameters: {'loss': 'exponential', 'learning_rate': 0.03859299376725511, 'n_estimators': 101, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:31,549] Trial 57 finished with value: 0.9171588227382218 and parameters: {'loss': 'exponential', 'learning_rate': 0.038193980574135984, 'n_estimators': 98, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:31,867] Trial 58 finished with value: 0.9128669772446596 and parameters: {'loss': 'exponential', 'learning_rate': 0.03888556536553232, 'n_estimators': 99, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:32,132] Trial 59 finished with value: 0.9157282075737011 and parameters: {'loss': 'exponential', 'learning_rate': 0.05279891713958939, 'n_estimators': 72, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:32,353] Trial 60 finished with value: 0.8913894085567905 and parameters: {'loss': 'exponential', 'learning_rate': 0.05193725419754611, 'n_estimators': 75, 'max_depth': 1, 'min_samples_split': 7, 'min_samples_leaf': 7}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:32,704] Trial 61 finished with value: 0.9157282075737011 and parameters: {'loss': 'exponential', 'learning_rate': 0.03524668181666653, 'n_estimators': 113, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:32,972] Trial 62 finished with value: 0.9128792047246983 and parameters: {'loss': 'exponential', 'learning_rate': 0.06023825598711627, 'n_estimators': 76, 'max_depth': 2, 'min_samples_split': 8, 'min_samples_leaf': 8}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:33,358] Trial 63 finished with value: 0.9028404436129759 and parameters: {'loss': 'exponential', 'learning_rate': 0.047655760214128956, 'n_estimators': 149, 'max_depth': 1, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:33,722] Trial 64 finished with value: 0.9114363620801389 and parameters: {'loss': 'exponential', 'learning_rate': 0.03244752850086746, 'n_estimators': 113, 'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:33,968] Trial 65 finished with value: 0.8971118692148735 and parameters: {'loss': 'exponential', 'learning_rate': 0.05269361327191362, 'n_estimators': 91, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 7}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:34,533] Trial 66 finished with value: 0.907150630326596 and parameters: {'loss': 'exponential', 'learning_rate': 0.0793593316117807, 'n_estimators': 180, 'max_depth': 2, 'min_samples_split': 9, 'min_samples_leaf': 8}. Best is trial 51 with value: 0.9171588227382218.
[I 2026-09-06 12:02:34,739] Trial 67 finished with value: 0.9200139393272441 and parameters: {'loss': 'exponential', 'learning_rate': 0.2431348744245794, 'n_estimators': 70, 'max_depth': 1, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:34,938] Trial 68 finished with value: 0.9114547033001968 and parameters: {'loss': 'exponential', 'learning_rate': 0.2913022983632631, 'n_estimators': 66, 'max_depth': 1, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:35,568] Trial 69 finished with value: 0.9057505838621718 and parameters: {'loss': 'exponential', 'learning_rate': 0.21838072968846325, 'n_estimators': 256, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 6}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:35,935] Trial 70 finished with value: 0.9057322426421139 and parameters: {'loss': 'exponential', 'learning_rate': 0.25684682231921163, 'n_estimators': 142, 'max_depth': 1, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:36,331] Trial 71 finished with value: 0.9171588227382218 and parameters: {'loss': 'exponential', 'learning_rate': 0.03511447940535653, 'n_estimators': 118, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:36,703] Trial 72 finished with value: 0.8957179364904686 and parameters: {'loss': 'exponential', 'learning_rate': 0.24881947723453374, 'n_estimators': 113, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:36,937] Trial 73 finished with value: 0.8957118227504494 and parameters: {'loss': 'exponential', 'learning_rate': 0.27477892915346813, 'n_estimators': 68, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 8}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:37,217] Trial 74 finished with value: 0.9128669772446596 and parameters: {'loss': 'exponential', 'learning_rate': 0.16293892347413447, 'n_estimators': 88, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 6}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:38,290] Trial 75 finished with value: 0.9128669772446596 and parameters: {'loss': 'exponential', 'learning_rate': 0.011557794482207291, 'n_estimators': 323, 'max_depth': 2, 'min_samples_split': 9, 'min_samples_leaf': 7}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:38,632] Trial 76 finished with value: 0.9042710587774966 and parameters: {'loss': 'exponential', 'learning_rate': 0.06584757043360707, 'n_estimators': 120, 'max_depth': 1, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:39,202] Trial 77 finished with value: 0.9128792047246983 and parameters: {'loss': 'exponential', 'learning_rate': 0.04487839683269172, 'n_estimators': 176, 'max_depth': 2, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:39,562] Trial 78 finished with value: 0.901446510888571 and parameters: {'loss': 'exponential', 'learning_rate': 0.1956834214077167, 'n_estimators': 84, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:39,752] Trial 79 finished with value: 0.888528178227749 and parameters: {'loss': 'exponential', 'learning_rate': 0.05657735712192756, 'n_estimators': 63, 'max_depth': 1, 'min_samples_split': 8, 'min_samples_leaf': 7}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:40,236] Trial 80 finished with value: 0.8914383184769451 and parameters: {'loss': 'exponential', 'learning_rate': 0.241989119539862, 'n_estimators': 149, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:40,587] Trial 81 finished with value: 0.9128608635046404 and parameters: {'loss': 'exponential', 'learning_rate': 0.03125565633304788, 'n_estimators': 101, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:40,904] Trial 82 finished with value: 0.9100057469156182 and parameters: {'loss': 'exponential', 'learning_rate': 0.035956926884313054, 'n_estimators': 93, 'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 7}. Best is trial 67 with value: 0.9200139393272441.

[I 2026-09-06 12:02:42,418] Trial 83 finished with value: 0.9000097819840308 and parameters: {'loss': 'exponential', 'learning_rate': 0.01864859005045289, 'n_estimators': 381, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 7}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:42,716] Trial 84 finished with value: 0.8813812161451646 and parameters: {'loss': 'exponential', 'learning_rate': 0.026153895071766436, 'n_estimators': 108, 'max_depth': 1, 'min_samples_split': 11, 'min_samples_leaf': 8}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:43,097] Trial 85 finished with value: 0.8857280852989007 and parameters: {'loss': 'exponential', 'learning_rate': 0.29940927185504135, 'n_estimators': 120, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:43,337] Trial 86 finished with value: 0.905713901422056 and parameters: {'loss': 'exponential', 'learning_rate': 0.04778063593893318, 'n_estimators': 51, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 8}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:43,785] Trial 87 finished with value: 0.9143037061491998 and parameters: {'loss': 'exponential', 'learning_rate': 0.06895288831647634, 'n_estimators': 134, 'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 6}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:44,120] Trial 88 finished with value: 0.9042710587774966 and parameters: {'loss': 'exponential', 'learning_rate': 0.0711696193280485, 'n_estimators': 135, 'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 6}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:44,863] Trial 89 finished with value: 0.8914383184769451 and parameters: {'loss': 'exponential', 'learning_rate': 0.10996905364654103, 'n_estimators': 231, 'max_depth': 2, 'min_samples_split': 4, 'min_samples_leaf': 6}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:45,187] Trial 90 finished with value: 0.8985730530794909 and parameters: {'loss': 'exponential', 'learning_rate': 0.08388966596627545, 'n_estimators': 75, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:45,603] Trial 91 finished with value: 0.9042955137375738 and parameters: {'loss': 'exponential', 'learning_rate': 0.13763590608379944, 'n_estimators': 126, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:45,922] Trial 92 finished with value: 0.9128669772446596 and parameters: {'loss': 'exponential', 'learning_rate': 0.04032605103129417, 'n_estimators': 95, 'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 7}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:46,200] Trial 93 finished with value: 0.9128730909846791 and parameters: {'loss': 'exponential', 'learning_rate': 0.2043483148708472, 'n_estimators': 102, 'max_depth': 1, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:46,684] Trial 94 finished with value: 0.8942812075859287 and parameters: {'loss': 'exponential', 'learning_rate': 0.18624952922321025, 'n_estimators': 147, 'max_depth': 2, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:47,035] Trial 95 finished with value: 0.905713901422056 and parameters: {'loss': 'exponential', 'learning_rate': 0.061312014360953904, 'n_estimators': 84, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:47,569] Trial 96 finished with value: 0.9157220938336819 and parameters: {'loss': 'exponential', 'learning_rate': 0.05440691234804344, 'n_estimators': 163, 'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:47,997] Trial 97 finished with value: 0.914291478669161 and parameters: {'loss': 'exponential', 'learning_rate': 0.09419023447426739, 'n_estimators': 163, 'max_depth': 1, 'min_samples_split': 3, 'min_samples_leaf': 8}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:48,752] Trial 98 finished with value: 0.8985791668195101 and parameters: {'loss': 'exponential', 'learning_rate': 0.07419487342947438, 'n_estimators': 191, 'max_depth': 3, 'min_samples_split': 16, 'min_samples_leaf': 9}. Best is trial 67 with value: 0.9200139393272441.
[I 2026-09-06 12:02:49,152] Trial 99 finished with value: 0.9157404350537397 and parameters: {'loss': 'exponential', 'learning_rate': 0.05210367477243545, 'n_estimators': 124, 'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 67 with value: 0.9200139393272441.

In [160]:
best_trial = study1.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'loss': 'exponential', 'learning_rate': 0.2431348744245794, 'n_estimators': 70, 'max_depth': 1, 'min_samples_split': 6, 'min_samples_leaf': 6}
Best trial accuracy: 0.9200139393272441

In [161]:
bo=GradientBoostingClassifier(**study1.best_trial.params,random_state=42)
bo.fit(X_train,y_train)
ypred5=bo.predict(X_test)
accuracy_score(ypred5,y_test)

0.88

In [162]:
from xgboost import XGBClassifier

def objective(trial):
    n_estimators=trial.suggest_int('n_estimators',50,500)
    max_depth=trial.suggest_int('max_depth',1,10)
    learning_rate=trial.suggest_float('learning_rate',0.01,0.3)
    min_child_weight=trial.suggest_int('min_child_weight',1,10)
    subsample=trial.suggest_float('subsample',0.5,1.0)
    colsample_bytree=trial.suggest_float('colsample_bytree',0.5,1.0)
    gamma=trial.suggest_float('gamma',0,5)
    reg_alpha=trial.suggest_float('reg_alpha',0,5)
    reg_lambda=trial.suggest_float('reg_lambda',0,5)

    xgb=XGBClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        learning_rate=learning_rate,
        min_child_weight=min_child_weight,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        gamma=gamma,
        reg_alpha=reg_alpha,
        reg_lambda=reg_lambda,
        n_jobs=-1,
        eval_metric='logloss'
    )

    score=cross_val_score(
        xgb,X_train,y_train,cv=3,scoring='accuracy'
    ).mean()

    return score

In [163]:
study2=optuna.create_study(direction='maximize')
study2.optimize(objective,n_trials=100)

[I 2026-09-06 12:05:35,905] A new study created in memory with name: no-name-e0224d1e-07ed-4265-a246-6e1ad4cab560
[I 2026-09-06 12:05:36,328] Trial 0 finished with value: 0.8985669393394716 and parameters: {'n_estimators': 366, 'max_depth': 4, 'learning_rate': 0.2527279203445778, 'min_child_weight': 2, 'subsample': 0.6155927536281276, 'colsample_bytree': 0.9194010705231932, 'gamma': 4.66654496627619, 'reg_alpha': 1.9767680786555841, 'reg_lambda': 3.075272561952084}. Best is trial 0 with value: 0.8985669393394716.
[I 2026-09-06 12:05:36,883] Trial 1 finished with value: 0.9085873592311361 and parameters: {'n_estimators': 448, 'max_depth': 6, 'learning_rate': 0.06289122022106215, 'min_child_weight': 7, 'subsample': 0.9496787059414304, 'colsample_bytree': 0.8774706727975932, 'gamma': 2.414977947275693, 'reg_alpha': 3.3535565098253297, 'reg_lambda': 0.28263546529119055}. Best is trial 1 with value: 0.9085873592311361.
[I 2026-09-06 12:05:37,098] Trial 2 finished with value: 0.8957240502304881 and parameters: {'n_estimators': 148, 'max_depth': 10, 'learning_rate': 0.22091866895971232, 'min_child_weight': 6, 'subsample': 0.5139093264806234, 'colsample_bytree': 0.757568685104349, 'gamma': 4.652152842030796, 'reg_alpha': 1.992391998854362, 'reg_lambda': 3.4064773783036397}. Best is trial 1 with value: 0.9085873592311361.
[I 2026-09-06 12:05:37,613] Trial 3 finished with value: 0.9028771260530917 and parameters: {'n_estimators': 433, 'max_depth': 7, 'learning_rate': 0.19732276076910962, 'min_child_weight': 6, 'subsample': 0.5984759252238392, 'colsample_bytree': 0.7957277972534217, 'gamma': 2.8909837176698283, 'reg_alpha': 0.539182191161261, 'reg_lambda': 0.3089725685730327}. Best is trial 1 with value: 0.9085873592311361.
[I 2026-09-06 12:05:37,937] Trial 4 finished with value: 0.9071567440666154 and parameters: {'n_estimators': 223, 'max_depth': 7, 'learning_rate': 0.09269345246152101, 'min_child_weight': 9, 'subsample': 0.9993614821319718, 'colsample_bytree': 0.8394462401556513, 'gamma': 2.659164476879274, 'reg_alpha': 3.4340703128947614, 'reg_lambda': 0.3276674357053516}. Best is trial 1 with value: 0.9085873592311361.
[I 2026-09-06 12:05:38,202] Trial 5 finished with value: 0.9128669772446596 and parameters: {'n_estimators': 189, 'max_depth': 9, 'learning_rate': 0.20274823865035718, 'min_child_weight': 5, 'subsample': 0.950507241277793, 'colsample_bytree': 0.5096267542161539, 'gamma': 4.865952280884845, 'reg_alpha': 0.9855503926764719, 'reg_lambda': 1.5774458071849085}. Best is trial 5 with value: 0.9128669772446596.
[I 2026-09-06 12:05:38,394] Trial 6 finished with value: 0.8957118227504495 and parameters: {'n_estimators': 115, 'max_depth': 4, 'learning_rate': 0.18367946554663506, 'min_child_weight': 5, 'subsample': 0.6295839710279043, 'colsample_bytree': 0.9311945707211522, 'gamma': 1.2660058359971886, 'reg_alpha': 4.873972978101881, 'reg_lambda': 1.2042566251338775}. Best is trial 5 with value: 0.9128669772446596.
[I 2026-09-06 12:05:38,585] Trial 7 finished with value: 0.914309819889219 and parameters: {'n_estimators': 123, 'max_depth': 2, 'learning_rate': 0.230379892108408, 'min_child_weight': 4, 'subsample': 0.9052205653907729, 'colsample_bytree': 0.6351920287215793, 'gamma': 4.171058345529824, 'reg_alpha': 0.37849456957408434, 'reg_lambda': 0.4232794626143027}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:39,541] Trial 8 finished with value: 0.9057261289020945 and parameters: {'n_estimators': 474, 'max_depth': 10, 'learning_rate': 0.10347816062479362, 'min_child_weight': 5, 'subsample': 0.7381100402303508, 'colsample_bytree': 0.9705596009723849, 'gamma': 0.14150531682412482, 'reg_alpha': 0.6133015728412677, 'reg_lambda': 3.412356911362054}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:39,915] Trial 9 finished with value: 0.8985730530794909 and parameters: {'n_estimators': 274, 'max_depth': 10, 'learning_rate': 0.24710607446275848, 'min_child_weight': 3, 'subsample': 0.6515091367550379, 'colsample_bytree': 0.9371569133194446, 'gamma': 3.9901214018646636, 'reg_alpha': 3.217353277542805, 'reg_lambda': 4.214197407732022}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:40,108] Trial 10 finished with value: 0.8071298436105302 and parameters: {'n_estimators': 71, 'max_depth': 1, 'learning_rate': 0.022750140021134485, 'min_child_weight': 10, 'subsample': 0.8257363077580461, 'colsample_bytree': 0.6300989157081109, 'gamma': 0.029244210197167497, 'reg_alpha': 4.825342035965422, 'reg_lambda': 4.931804635328162}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:40,653] Trial 11 finished with value: 0.9114363620801389 and parameters: {'n_estimators': 239, 'max_depth': 1, 'learning_rate': 0.2947624948434835, 'min_child_weight': 3, 'subsample': 0.8886354980873346, 'colsample_bytree': 0.5185670089631024, 'gamma': 3.710588290701054, 'reg_alpha': 0.03039811491211264, 'reg_lambda': 1.8094972722541325}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:41,212] Trial 12 finished with value: 0.9057200151620752 and parameters: {'n_estimators': 191, 'max_depth': 3, 'learning_rate': 0.15194428590514136, 'min_child_weight': 1, 'subsample': 0.8445717130690981, 'colsample_bytree': 0.5190780622463715, 'gamma': 4.861670875324608, 'reg_alpha': 1.3931947277531889, 'reg_lambda': 1.7517232849419413}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:42,022] Trial 13 finished with value: 0.9085751317510974 and parameters: {'n_estimators': 312, 'max_depth': 8, 'learning_rate': 0.1515743660981912, 'min_child_weight': 4, 'subsample': 0.917839138153659, 'colsample_bytree': 0.630012771509847, 'gamma': 3.7188221324384796, 'reg_alpha': 1.174511270171754, 'reg_lambda': 1.416799963949476}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:42,264] Trial 14 finished with value: 0.9042955137375738 and parameters: {'n_estimators': 68, 'max_depth': 3, 'learning_rate': 0.294560729597487, 'min_child_weight': 8, 'subsample': 0.7829859520703222, 'colsample_bytree': 0.615646322727166, 'gamma': 4.1166522644029895, 'reg_alpha': 0.18761492593846896, 'reg_lambda': 2.27195084884609}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:42,679] Trial 15 finished with value: 0.9142792511891225 and parameters: {'n_estimators': 137, 'max_depth': 5, 'learning_rate': 0.15963795383343396, 'min_child_weight': 4, 'subsample': 0.9997410802626937, 'colsample_bytree': 0.5740534781699328, 'gamma': 3.1301186945255424, 'reg_alpha': 1.1608876916131958, 'reg_lambda': 1.0301330895005738}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:43,067] Trial 16 finished with value: 0.9114424758201581 and parameters: {'n_estimators': 135, 'max_depth': 5, 'learning_rate': 0.14472000266572585, 'min_child_weight': 3, 'subsample': 0.9946793055392438, 'colsample_bytree': 0.7309869865211831, 'gamma': 3.186766484728568, 'reg_alpha': 1.9223541433010511, 'reg_lambda': 0.8924727068799063}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:43,481] Trial 17 finished with value: 0.9114241346001003 and parameters: {'n_estimators': 111, 'max_depth': 2, 'learning_rate': 0.24731289657611305, 'min_child_weight': 1, 'subsample': 0.8809845351856324, 'colsample_bytree': 0.6758237093782137, 'gamma': 1.9945729658840852, 'reg_alpha': 2.427804543923945, 'reg_lambda': 0.7634585391129658}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:43,982] Trial 18 finished with value: 0.9014403971485517 and parameters: {'n_estimators': 170, 'max_depth': 5, 'learning_rate': 0.11234460350456474, 'min_child_weight': 4, 'subsample': 0.8175342074759405, 'colsample_bytree': 0.5980104606429447, 'gamma': 3.302864547709836, 'reg_alpha': 1.4737619445386236, 'reg_lambda': 2.4089373416518174}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:44,174] Trial 19 finished with value: 0.9042893999975545 and parameters: {'n_estimators': 51, 'max_depth': 2, 'learning_rate': 0.1729438771490343, 'min_child_weight': 7, 'subsample': 0.7263352598519017, 'colsample_bytree': 0.6992000401254295, 'gamma': 2.010528884382023, 'reg_alpha': 2.6028164997371843, 'reg_lambda': 0.01770313810458357}. Best is trial 7 with value: 0.914309819889219.

[I 2026-09-06 12:05:44,786] Trial 20 finished with value: 0.9114485895601776 and parameters: {'n_estimators': 325, 'max_depth': 5, 'learning_rate': 0.2269282063325172, 'min_child_weight': 2, 'subsample': 0.9380953659059725, 'colsample_bytree': 0.5583824350009303, 'gamma': 1.3236828617028735, 'reg_alpha': 0.704648134204999, 'reg_lambda': 0.9917516600644697}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:45,203] Trial 21 finished with value: 0.9100302018756953 and parameters: {'n_estimators': 201, 'max_depth': 8, 'learning_rate': 0.20576909243179267, 'min_child_weight': 5, 'subsample': 0.9641150683407224, 'colsample_bytree': 0.5712561161641291, 'gamma': 4.174810104478654, 'reg_alpha': 1.0169170526970466, 'reg_lambda': 1.6586351686566503}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:45,517] Trial 22 finished with value: 0.9057322426421139 and parameters: {'n_estimators': 105, 'max_depth': 9, 'learning_rate': 0.1663122242659036, 'min_child_weight': 4, 'subsample': 0.9052608734872796, 'colsample_bytree': 0.5013807524452459, 'gamma': 4.292371438517106, 'reg_alpha': 0.895615085544217, 'reg_lambda': 2.2500262940526587}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:45,933] Trial 23 finished with value: 0.9114424758201581 and parameters: {'n_estimators': 169, 'max_depth': 6, 'learning_rate': 0.2676644194175537, 'min_child_weight': 6, 'subsample': 0.8802147793858218, 'colsample_bytree': 0.6619446933314674, 'gamma': 3.469342366590748, 'reg_alpha': 0.3135025811629366, 'reg_lambda': 0.7265235461838899}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:46,443] Trial 24 finished with value: 0.912854749764621 and parameters: {'n_estimators': 247, 'max_depth': 3, 'learning_rate': 0.1312204670736165, 'min_child_weight': 4, 'subsample': 0.9673952152028014, 'colsample_bytree': 0.5562088493917149, 'gamma': 4.5235822411049815, 'reg_alpha': 1.4609594739966845, 'reg_lambda': 1.3343781312720313}. Best is trial 7 with value: 0.914309819889219.
[I 2026-09-06 12:05:46,713] Trial 25 finished with value: 0.9157220938336819 and parameters: {'n_estimators': 94, 'max_depth': 8, 'learning_rate': 0.21864619440831837, 'min_child_weight': 5, 'subsample': 0.8582502306646318, 'colsample_bytree': 0.5795610599150783, 'gamma': 4.990647460289555, 'reg_alpha': 1.6381020518584073, 'reg_lambda': 1.9626405377639662}. Best is trial 25 with value: 0.9157220938336819.
[I 2026-09-06 12:05:46,967] Trial 26 finished with value: 0.9071384028465573 and parameters: {'n_estimators': 93, 'max_depth': 6, 'learning_rate': 0.2239402960523587, 'min_child_weight': 2, 'subsample': 0.8549862206652048, 'colsample_bytree': 0.591387570912504, 'gamma': 4.98027431927903, 'reg_alpha': 1.7601281138446718, 'reg_lambda': 2.6500563518223403}. Best is trial 25 with value: 0.9157220938336819.
[I 2026-09-06 12:05:47,291] Trial 27 finished with value: 0.9043016274775932 and parameters: {'n_estimators': 141, 'max_depth': 4, 'learning_rate': 0.26600899184982785, 'min_child_weight': 7, 'subsample': 0.7881042917592317, 'colsample_bytree': 0.6682667521341159, 'gamma': 3.813082846565104, 'reg_alpha': 2.485000954283022, 'reg_lambda': 0.5231932442932736}. Best is trial 25 with value: 0.9157220938336819.
[I 2026-09-06 12:05:47,542] Trial 28 finished with value: 0.9100057469156182 and parameters: {'n_estimators': 81, 'max_depth': 7, 'learning_rate': 0.185761236589743, 'min_child_weight': 3, 'subsample': 0.917381631894506, 'colsample_bytree': 0.7375376134465079, 'gamma': 4.377050238528703, 'reg_alpha': 0.5020960182675864, 'reg_lambda': 1.0938212325150118}. Best is trial 25 with value: 0.9157220938336819.
[I 2026-09-06 12:05:47,878] Trial 29 finished with value: 0.9028648985730531 and parameters: {'n_estimators': 142, 'max_depth': 2, 'learning_rate': 0.23103943166901797, 'min_child_weight': 6, 'subsample': 0.771426311617767, 'colsample_bytree': 0.5553979587216041, 'gamma': 2.9731705988218105, 'reg_alpha': 2.0421697010509234, 'reg_lambda': 2.03417544157535}. Best is trial 25 with value: 0.9157220938336819.
[I 2026-09-06 12:05:48,088] Trial 30 finished with value: 0.9057077876820365 and parameters: {'n_estimators': 55, 'max_depth': 4, 'learning_rate': 0.2749038599073861, 'min_child_weight': 4, 'subsample': 0.8632247076936796, 'colsample_bytree': 0.6491594362842761, 'gamma': 4.591323939754254, 'reg_alpha': 2.8009093038698722, 'reg_lambda': 3.2485492098913804}. Best is trial 25 with value: 0.9157220938336819.
[I 2026-09-06 12:05:48,487] Trial 31 finished with value: 0.9171527089982026 and parameters: {'n_estimators': 183, 'max_depth': 9, 'learning_rate': 0.1897456615096879, 'min_child_weight': 5, 'subsample': 0.9363255075290404, 'colsample_bytree': 0.5388793618303316, 'gamma': 4.78892822768999, 'reg_alpha': 1.1056949354551309, 'reg_lambda': 2.709838052701852}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:48,857] Trial 32 finished with value: 0.9114363620801389 and parameters: {'n_estimators': 166, 'max_depth': 9, 'learning_rate': 0.20933328091987558, 'min_child_weight': 5, 'subsample': 0.9307646275657491, 'colsample_bytree': 0.5923945829258325, 'gamma': 4.404894510681261, 'reg_alpha': 1.2569657461984765, 'reg_lambda': 2.835943093507284}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:49,197] Trial 33 finished with value: 0.9128608635046404 and parameters: {'n_estimators': 125, 'max_depth': 8, 'learning_rate': 0.1708397260852133, 'min_child_weight': 6, 'subsample': 0.9738391408162065, 'colsample_bytree': 0.5336467033604441, 'gamma': 4.746749642009964, 'reg_alpha': 1.6134513451693406, 'reg_lambda': 2.9129627670626306}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:49,635] Trial 34 finished with value: 0.9128669772446596 and parameters: {'n_estimators': 213, 'max_depth': 9, 'learning_rate': 0.1965948572998655, 'min_child_weight': 4, 'subsample': 0.9403211010214156, 'colsample_bytree': 0.7021985824738952, 'gamma': 3.935893605119122, 'reg_alpha': 0.8090676937354614, 'reg_lambda': 0.09712821904180569}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:50,015] Trial 35 finished with value: 0.9128669772446596 and parameters: {'n_estimators': 157, 'max_depth': 8, 'learning_rate': 0.1284685044048478, 'min_child_weight': 5, 'subsample': 0.9032025676355852, 'colsample_bytree': 0.5785703152163684, 'gamma': 3.4030453392891102, 'reg_alpha': 2.078788012125671, 'reg_lambda': 3.7848878803333554}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:50,697] Trial 36 finished with value: 0.9100179743956568 and parameters: {'n_estimators': 392, 'max_depth': 7, 'learning_rate': 0.2366082895318083, 'min_child_weight': 7, 'subsample': 0.9982289860985591, 'colsample_bytree': 0.6164077657982485, 'gamma': 2.4495116266158528, 'reg_alpha': 0.4547522342584074, 'reg_lambda': 0.5896443008677021}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:51,244] Trial 37 finished with value: 0.9057200151620752 and parameters: {'n_estimators': 268, 'max_depth': 6, 'learning_rate': 0.0734301209173249, 'min_child_weight': 3, 'subsample': 0.5607793511535302, 'colsample_bytree': 0.8005603121203196, 'gamma': 4.990854743332578, 'reg_alpha': 1.0541609985707694, 'reg_lambda': 1.9871832220535035}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:51,479] Trial 38 finished with value: 0.8999975545039923 and parameters: {'n_estimators': 91, 'max_depth': 10, 'learning_rate': 0.2141057302512151, 'min_child_weight': 5, 'subsample': 0.8101615360382564, 'colsample_bytree': 0.5382877204581924, 'gamma': 4.6338877104811, 'reg_alpha': 3.9846921441847716, 'reg_lambda': 0.31556811754076713}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:51,856] Trial 39 finished with value: 0.9085812454911167 and parameters: {'n_estimators': 183, 'max_depth': 9, 'learning_rate': 0.18577451552971247, 'min_child_weight': 8, 'subsample': 0.9728042150782118, 'colsample_bytree': 0.878151425991144, 'gamma': 2.861969144319727, 'reg_alpha': 2.23047622633831, 'reg_lambda': 2.554373502376933}. Best is trial 31 with value: 0.9171527089982026.

[I 2026-09-06 12:05:52,155] Trial 40 finished with value: 0.9043077412176125 and parameters: {'n_estimators': 124, 'max_depth': 7, 'learning_rate': 0.2517420749293558, 'min_child_weight': 6, 'subsample': 0.8405044361998935, 'colsample_bytree': 0.6418525947774195, 'gamma': 3.6452760250904124, 'reg_alpha': 1.651774323000037, 'reg_lambda': 1.4359848872507857}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:52,588] Trial 41 finished with value: 0.915728207573701 and parameters: {'n_estimators': 205, 'max_depth': 9, 'learning_rate': 0.19584442903821223, 'min_child_weight': 5, 'subsample': 0.9394913780245974, 'colsample_bytree': 0.5050063328166616, 'gamma': 4.702016355982903, 'reg_alpha': 0.835320313599399, 'reg_lambda': 1.201144116420008}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:53,059] Trial 42 finished with value: 0.9085812454911167 and parameters: {'n_estimators': 246, 'max_depth': 10, 'learning_rate': 0.1921630504812858, 'min_child_weight': 5, 'subsample': 0.9481682065641751, 'colsample_bytree': 0.5420649316887416, 'gamma': 4.718081911953552, 'reg_alpha': 0.0058779200702524514, 'reg_lambda': 1.2361285479634807}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:53,447] Trial 43 finished with value: 0.9100057469156182 and parameters: {'n_estimators': 200, 'max_depth': 9, 'learning_rate': 0.16720132534292842, 'min_child_weight': 4, 'subsample': 0.8899135915011505, 'colsample_bytree': 0.5005099353220168, 'gamma': 4.134519093090922, 'reg_alpha': 0.7482929079877092, 'reg_lambda': 1.9600080898017695}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:53,876] Trial 44 finished with value: 0.9071445165865768 and parameters: {'n_estimators': 223, 'max_depth': 8, 'learning_rate': 0.21249573846567998, 'min_child_weight': 6, 'subsample': 0.9235316123005879, 'colsample_bytree': 0.6045705424657465, 'gamma': 4.453631453279812, 'reg_alpha': 1.2526811095030073, 'reg_lambda': 0.4744485046258444}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:54,203] Trial 45 finished with value: 0.9100057469156182 and parameters: {'n_estimators': 151, 'max_depth': 10, 'learning_rate': 0.23912400761028033, 'min_child_weight': 5, 'subsample': 0.9814683071199869, 'colsample_bytree': 0.5774040601495072, 'gamma': 4.761078848320172, 'reg_alpha': 0.3809576296763231, 'reg_lambda': 1.5269020909524391}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:54,449] Trial 46 finished with value: 0.9114424758201581 and parameters: {'n_estimators': 101, 'max_depth': 1, 'learning_rate': 0.15832064089687975, 'min_child_weight': 3, 'subsample': 0.8694315370093444, 'colsample_bytree': 0.5301881776905885, 'gamma': 0.5258262503602349, 'reg_alpha': 1.1074211635175073, 'reg_lambda': 0.9270782574259181}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:55,015] Trial 47 finished with value: 0.9085812454911167 and parameters: {'n_estimators': 286, 'max_depth': 9, 'learning_rate': 0.13649548633546843, 'min_child_weight': 4, 'subsample': 0.9568203202996846, 'colsample_bytree': 0.620353718227943, 'gamma': 3.923803790349976, 'reg_alpha': 1.7799360557235508, 'reg_lambda': 1.1578995602808242}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:55,512] Trial 48 finished with value: 0.9114363620801389 and parameters: {'n_estimators': 228, 'max_depth': 4, 'learning_rate': 0.18167930443457603, 'min_child_weight': 6, 'subsample': 0.9001782523684805, 'colsample_bytree': 0.5648803902605956, 'gamma': 4.99212805980076, 'reg_alpha': 0.5738715193191789, 'reg_lambda': 3.5577780985294742}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:55,914] Trial 49 finished with value: 0.9028587848330338 and parameters: {'n_estimators': 182, 'max_depth': 8, 'learning_rate': 0.20157735190384185, 'min_child_weight': 3, 'subsample': 0.6962627800396152, 'colsample_bytree': 0.5232282705048104, 'gamma': 4.25695812406876, 'reg_alpha': 0.19240446386882393, 'reg_lambda': 1.8000424774496786}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:56,194] Trial 50 finished with value: 0.9071506303265959 and parameters: {'n_estimators': 120, 'max_depth': 6, 'learning_rate': 0.2183642988370243, 'min_child_weight': 5, 'subsample': 0.8424806340851294, 'colsample_bytree': 0.9908072045659424, 'gamma': 4.571110000869901, 'reg_alpha': 1.357241348783632, 'reg_lambda': 4.895941840671222}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:56,565] Trial 51 finished with value: 0.914291478669161 and parameters: {'n_estimators': 186, 'max_depth': 9, 'learning_rate': 0.19740973055364902, 'min_child_weight': 5, 'subsample': 0.952258905586491, 'colsample_bytree': 0.5004474939510009, 'gamma': 4.822695417200067, 'reg_alpha': 0.9241115599910438, 'reg_lambda': 1.6552098933679766}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:57,133] Trial 52 finished with value: 0.9114302483401197 and parameters: {'n_estimators': 200, 'max_depth': 9, 'learning_rate': 0.035569465961174315, 'min_child_weight': 4, 'subsample': 0.9473270762547047, 'colsample_bytree': 0.5166077020635541, 'gamma': 4.687448783558808, 'reg_alpha': 0.8351219450836996, 'reg_lambda': 2.2099301751330658}. Best is trial 31 with value: 0.9171527089982026.
[I 2026-09-06 12:05:58,052] Trial 53 finished with value: 0.9185894379027425 and parameters: {'n_estimators': 490, 'max_depth': 10, 'learning_rate': 0.180069769624633, 'min_child_weight': 5, 'subsample': 0.9835158966110434, 'colsample_bytree': 0.5798007763471013, 'gamma': 4.885314530982971, 'reg_alpha': 0.9056875464332528, 'reg_lambda': 0.7400350582594433}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:05:58,803] Trial 54 finished with value: 0.9171527089982026 and parameters: {'n_estimators': 451, 'max_depth': 10, 'learning_rate': 0.1943391778516757, 'min_child_weight': 5, 'subsample': 0.9179577360619458, 'colsample_bytree': 0.5456152925589678, 'gamma': 4.853484831131423, 'reg_alpha': 0.6532920110007886, 'reg_lambda': 0.22602134738160595}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:05:59,593] Trial 55 finished with value: 0.9114424758201581 and parameters: {'n_estimators': 496, 'max_depth': 10, 'learning_rate': 0.22081481597588232, 'min_child_weight': 6, 'subsample': 0.9184163987827673, 'colsample_bytree': 0.5410014741568079, 'gamma': 4.06886827866021, 'reg_alpha': 0.6521511543530715, 'reg_lambda': 0.22795796949627267}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:00,324] Trial 56 finished with value: 0.9143037061491998 and parameters: {'n_estimators': 441, 'max_depth': 10, 'learning_rate': 0.18213620399080274, 'min_child_weight': 5, 'subsample': 0.8784720801480081, 'colsample_bytree': 0.592110800245863, 'gamma': 4.398540750981305, 'reg_alpha': 0.22461640765367957, 'reg_lambda': 0.7998915279584197}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:01,031] Trial 57 finished with value: 0.9128669772446596 and parameters: {'n_estimators': 463, 'max_depth': 10, 'learning_rate': 0.23910002569178554, 'min_child_weight': 7, 'subsample': 0.9030923543886562, 'colsample_bytree': 0.6351690194007757, 'gamma': 4.875202093554659, 'reg_alpha': 1.5002260265170317, 'reg_lambda': 0.6811417936362023}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:01,780] Trial 58 finished with value: 0.9114547033001967 and parameters: {'n_estimators': 490, 'max_depth': 10, 'learning_rate': 0.17359101407204902, 'min_child_weight': 10, 'subsample': 0.930485236742704, 'colsample_bytree': 0.6074854482023115, 'gamma': 4.252805097905877, 'reg_alpha': 0.6737180584286341, 'reg_lambda': 0.42723643240566234}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:02,457] Trial 59 finished with value: 0.9057322426421139 and parameters: {'n_estimators': 417, 'max_depth': 9, 'learning_rate': 0.146730489776477, 'min_child_weight': 2, 'subsample': 0.9873111607157933, 'colsample_bytree': 0.5534138795128356, 'gamma': 4.5113216521798405, 'reg_alpha': 0.9555839174876406, 'reg_lambda': 0.25264957062247906}. Best is trial 53 with value: 0.9185894379027425.

[I 2026-09-06 12:06:03,149] Trial 60 finished with value: 0.9043077412176124 and parameters: {'n_estimators': 418, 'max_depth': 8, 'learning_rate': 0.2019834505850076, 'min_child_weight': 5, 'subsample': 0.8310002179358, 'colsample_bytree': 0.5789244611364097, 'gamma': 4.830231004970807, 'reg_alpha': 0.3320149825983151, 'reg_lambda': 0.017643903022462992}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:03,827] Trial 61 finished with value: 0.9114424758201581 and parameters: {'n_estimators': 437, 'max_depth': 10, 'learning_rate': 0.18285268243565544, 'min_child_weight': 5, 'subsample': 0.8779558514584389, 'colsample_bytree': 0.5944442918545814, 'gamma': 4.357831305395497, 'reg_alpha': 0.18729052788827608, 'reg_lambda': 0.7623271460845613}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:04,446] Trial 62 finished with value: 0.9071506303265959 and parameters: {'n_estimators': 364, 'max_depth': 10, 'learning_rate': 0.1891827188522238, 'min_child_weight': 6, 'subsample': 0.860327872441379, 'colsample_bytree': 0.5599752394923789, 'gamma': 4.549987051034705, 'reg_alpha': 0.1807837811442247, 'reg_lambda': 0.5839246722382403}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:05,202] Trial 63 finished with value: 0.9128608635046404 and parameters: {'n_estimators': 466, 'max_depth': 10, 'learning_rate': 0.15910519775010173, 'min_child_weight': 4, 'subsample': 0.8938588502760308, 'colsample_bytree': 0.5858158205534154, 'gamma': 4.989194204550737, 'reg_alpha': 0.5401996369292816, 'reg_lambda': 0.9036002650589298}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:05,928] Trial 64 finished with value: 0.9157220938336819 and parameters: {'n_estimators': 452, 'max_depth': 9, 'learning_rate': 0.1790641343410999, 'min_child_weight': 5, 'subsample': 0.9103338130563636, 'colsample_bytree': 0.685564326003312, 'gamma': 4.406052847516545, 'reg_alpha': 1.1986299954383033, 'reg_lambda': 1.3071521677064466}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:06,705] Trial 65 finished with value: 0.9114424758201581 and parameters: {'n_estimators': 484, 'max_depth': 9, 'learning_rate': 0.20809337901693994, 'min_child_weight': 6, 'subsample': 0.9144078979827953, 'colsample_bytree': 0.6880662398492818, 'gamma': 4.056433916343824, 'reg_alpha': 1.3030759647742054, 'reg_lambda': 1.2417399489576242}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:07,272] Trial 66 finished with value: 0.9171588227382218 and parameters: {'n_estimators': 342, 'max_depth': 9, 'learning_rate': 0.26243964960571553, 'min_child_weight': 4, 'subsample': 0.9662250080195953, 'colsample_bytree': 0.6545314700460748, 'gamma': 3.5731186132948585, 'reg_alpha': 1.1338184640041806, 'reg_lambda': 1.3776683390768876}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:07,869] Trial 67 finished with value: 0.914291478669161 and parameters: {'n_estimators': 364, 'max_depth': 8, 'learning_rate': 0.28033917550244003, 'min_child_weight': 4, 'subsample': 0.9589054061195841, 'colsample_bytree': 0.7202779595242648, 'gamma': 3.5997253965396245, 'reg_alpha': 1.1057237920298395, 'reg_lambda': 1.4092535328175682}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:08,438] Trial 68 finished with value: 0.9157220938336819 and parameters: {'n_estimators': 347, 'max_depth': 9, 'learning_rate': 0.25945502756638933, 'min_child_weight': 5, 'subsample': 0.9378611318456925, 'colsample_bytree': 0.7061718597345105, 'gamma': 3.796427551574474, 'reg_alpha': 1.8506335333363573, 'reg_lambda': 1.0919572528644845}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:09,111] Trial 69 finished with value: 0.9128730909846788 and parameters: {'n_estimators': 403, 'max_depth': 8, 'learning_rate': 0.17832278272074678, 'min_child_weight': 5, 'subsample': 0.9769107289693267, 'colsample_bytree': 0.7677550301075067, 'gamma': 4.666406379784642, 'reg_alpha': 1.5410298703224947, 'reg_lambda': 1.6111049112033922}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:09,857] Trial 70 finished with value: 0.9100057469156182 and parameters: {'n_estimators': 458, 'max_depth': 9, 'learning_rate': 0.11372565451987574, 'min_child_weight': 4, 'subsample': 0.9318667653536754, 'colsample_bytree': 0.6545445733852006, 'gamma': 4.839778204143863, 'reg_alpha': 1.2165939110858957, 'reg_lambda': 2.1575848356831084}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:10,406] Trial 71 finished with value: 0.9142975924091804 and parameters: {'n_estimators': 320, 'max_depth': 9, 'learning_rate': 0.26239020088775183, 'min_child_weight': 5, 'subsample': 0.9374833689090488, 'colsample_bytree': 0.684320387279542, 'gamma': 3.850519315496302, 'reg_alpha': 1.9253412086989483, 'reg_lambda': 1.0480238085782534}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:10,987] Trial 72 finished with value: 0.9114363620801389 and parameters: {'n_estimators': 347, 'max_depth': 9, 'learning_rate': 0.2937890534972607, 'min_child_weight': 5, 'subsample': 0.9667330333991642, 'colsample_bytree': 0.7065692281366786, 'gamma': 3.5363778516770754, 'reg_alpha': 1.7385344918982095, 'reg_lambda': 1.2874195118201501}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:11,713] Trial 73 finished with value: 0.910024088135676 and parameters: {'n_estimators': 478, 'max_depth': 8, 'learning_rate': 0.25740531060093486, 'min_child_weight': 6, 'subsample': 0.9880940751474846, 'colsample_bytree': 0.7702819826826101, 'gamma': 3.1815380139112075, 'reg_alpha': 2.153833391839825, 'reg_lambda': 1.8459223151106923}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:12,325] Trial 74 finished with value: 0.9142975924091804 and parameters: {'n_estimators': 384, 'max_depth': 9, 'learning_rate': 0.2312765197274828, 'min_child_weight': 5, 'subsample': 0.9099558004908228, 'colsample_bytree': 0.6705145304606864, 'gamma': 3.7681567624721155, 'reg_alpha': 1.8497607353855672, 'reg_lambda': 1.0662644901248715}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:12,811] Trial 75 finished with value: 0.9028648985730531 and parameters: {'n_estimators': 280, 'max_depth': 8, 'learning_rate': 0.27275954444865413, 'min_child_weight': 4, 'subsample': 0.9567235604360274, 'colsample_bytree': 0.7370582552117669, 'gamma': 3.3652433450969124, 'reg_alpha': 1.3847059531140626, 'reg_lambda': 1.450301592846556}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:13,328] Trial 76 finished with value: 0.908569018011078 and parameters: {'n_estimators': 304, 'max_depth': 9, 'learning_rate': 0.2467960727334389, 'min_child_weight': 5, 'subsample': 0.9341969705618186, 'colsample_bytree': 0.7509747957230434, 'gamma': 4.181766601867299, 'reg_alpha': 0.9768670350577031, 'reg_lambda': 2.478167189391134}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:13,994] Trial 77 finished with value: 0.9014342834085324 and parameters: {'n_estimators': 423, 'max_depth': 10, 'learning_rate': 0.2808622212317029, 'min_child_weight': 6, 'subsample': 0.9209625661391059, 'colsample_bytree': 0.7140435910949768, 'gamma': 4.62383096169701, 'reg_alpha': 4.428289611271826, 'reg_lambda': 3.089223538323489}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:14,560] Trial 78 finished with value: 0.909999633175599 and parameters: {'n_estimators': 338, 'max_depth': 7, 'learning_rate': 0.19473247458607684, 'min_child_weight': 4, 'subsample': 0.9451551960423725, 'colsample_bytree': 0.543759992251784, 'gamma': 4.430900466200036, 'reg_alpha': 1.6244271288569947, 'reg_lambda': 2.370983465133796}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:15,030] Trial 79 finished with value: 0.8971546653950088 and parameters: {'n_estimators': 260, 'max_depth': 9, 'learning_rate': 0.16477337620474278, 'min_child_weight': 7, 'subsample': 0.5135578967649408, 'colsample_bytree': 0.5120015674831759, 'gamma': 4.9051872657318984, 'reg_alpha': 0.8203050057276756, 'reg_lambda': 0.15426214688226736}. Best is trial 53 with value: 0.9185894379027425.

[I 2026-09-06 12:06:15,675] Trial 80 finished with value: 0.9100179743956568 and parameters: {'n_estimators': 378, 'max_depth': 10, 'learning_rate': 0.17628023834529555, 'min_child_weight': 5, 'subsample': 0.9713244677580479, 'colsample_bytree': 0.6265054360497551, 'gamma': 3.03894238415788, 'reg_alpha': 1.1582490795922886, 'reg_lambda': 0.8471680925686853}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:16,381] Trial 81 finished with value: 0.9057261289020945 and parameters: {'n_estimators': 452, 'max_depth': 1, 'learning_rate': 0.23097580511768068, 'min_child_weight': 4, 'subsample': 0.890487967197166, 'colsample_bytree': 0.6542955292925893, 'gamma': 3.93215567196339, 'reg_alpha': 0.7052962810821265, 'reg_lambda': 0.4460059896063835}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:16,890] Trial 82 finished with value: 0.9114302483401197 and parameters: {'n_estimators': 298, 'max_depth': 3, 'learning_rate': 0.21834287059954233, 'min_child_weight': 3, 'subsample': 0.8504649945473891, 'colsample_bytree': 0.6831288511770068, 'gamma': 4.240066294179665, 'reg_alpha': 0.4954246700562686, 'reg_lambda': 0.6356920155570525}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:17,101] Trial 83 finished with value: 0.9171588227382218 and parameters: {'n_estimators': 63, 'max_depth': 9, 'learning_rate': 0.24776840049081805, 'min_child_weight': 4, 'subsample': 0.8732901647631106, 'colsample_bytree': 0.6361482644735538, 'gamma': 4.769545188106958, 'reg_alpha': 1.0642015158883573, 'reg_lambda': 0.37678167265305407}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:17,297] Trial 84 finished with value: 0.9014403971485517 and parameters: {'n_estimators': 64, 'max_depth': 8, 'learning_rate': 0.24847695738029085, 'min_child_weight': 5, 'subsample': 0.7982227423012997, 'colsample_bytree': 0.5498454607480553, 'gamma': 4.835468127776281, 'reg_alpha': 1.0404606883797978, 'reg_lambda': 0.9752986332003774}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:17,531] Trial 85 finished with value: 0.905713901422056 and parameters: {'n_estimators': 89, 'max_depth': 9, 'learning_rate': 0.2592766823826897, 'min_child_weight': 4, 'subsample': 0.8659917835509813, 'colsample_bytree': 0.5273176824652429, 'gamma': 4.717503259644568, 'reg_alpha': 2.2980263717266887, 'reg_lambda': 1.1879142011727737}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:18,260] Trial 86 finished with value: 0.9128608635046404 and parameters: {'n_estimators': 471, 'max_depth': 9, 'learning_rate': 0.21011749970672416, 'min_child_weight': 5, 'subsample': 0.9992606905217897, 'colsample_bytree': 0.6445057993505904, 'gamma': 4.463782898593028, 'reg_alpha': 1.4199095320865287, 'reg_lambda': 0.3506035320234909}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:18,481] Trial 87 finished with value: 0.914291478669161 and parameters: {'n_estimators': 73, 'max_depth': 8, 'learning_rate': 0.24281993389873843, 'min_child_weight': 5, 'subsample': 0.9090290489318003, 'colsample_bytree': 0.6138516201301262, 'gamma': 4.723600884415735, 'reg_alpha': 1.2743693127234665, 'reg_lambda': 2.8453911217302723}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:19,193] Trial 88 finished with value: 0.9100057469156182 and parameters: {'n_estimators': 450, 'max_depth': 10, 'learning_rate': 0.2894476645364303, 'min_child_weight': 6, 'subsample': 0.9241982074838715, 'colsample_bytree': 0.6916604027802391, 'gamma': 4.571691717881608, 'reg_alpha': 0.852654156923861, 'reg_lambda': 2.7078861852752354}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:19,843] Trial 89 finished with value: 0.9085812454911167 and parameters: {'n_estimators': 406, 'max_depth': 9, 'learning_rate': 0.19162269132360513, 'min_child_weight': 3, 'subsample': 0.8753162607431147, 'colsample_bytree': 0.5668495732369812, 'gamma': 4.3240728910851, 'reg_alpha': 1.6869591988094512, 'reg_lambda': 1.6948205735073694}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:20,040] Trial 90 finished with value: 0.9085751317510974 and parameters: {'n_estimators': 52, 'max_depth': 10, 'learning_rate': 0.2261993497626118, 'min_child_weight': 4, 'subsample': 0.826694029117941, 'colsample_bytree': 0.602272439906795, 'gamma': 4.927769435343306, 'reg_alpha': 1.5287880993059622, 'reg_lambda': 1.374021492450369}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:20,264] Trial 91 finished with value: 0.9042771725175158 and parameters: {'n_estimators': 80, 'max_depth': 5, 'learning_rate': 0.2546268172325479, 'min_child_weight': 4, 'subsample': 0.8947497221492258, 'colsample_bytree': 0.6679631699822302, 'gamma': 4.088969720697833, 'reg_alpha': 0.6156428938845111, 'reg_lambda': 0.15012129625503717}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:20,561] Trial 92 finished with value: 0.9157220938336819 and parameters: {'n_estimators': 130, 'max_depth': 10, 'learning_rate': 0.20166052979988844, 'min_child_weight': 5, 'subsample': 0.9492800244494684, 'colsample_bytree': 0.6412669145613537, 'gamma': 4.766764499763752, 'reg_alpha': 0.9589143873561456, 'reg_lambda': 0.5282404421941037}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:20,865] Trial 93 finished with value: 0.9085995867111748 and parameters: {'n_estimators': 132, 'max_depth': 10, 'learning_rate': 0.20070688994890465, 'min_child_weight': 5, 'subsample': 0.9622159755941199, 'colsample_bytree': 0.6570427970051939, 'gamma': 4.8072416053849585, 'reg_alpha': 1.028251559687832, 'reg_lambda': 0.5278187890249081}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:21,128] Trial 94 finished with value: 0.9142975924091803 and parameters: {'n_estimators': 107, 'max_depth': 10, 'learning_rate': 0.18836170144890602, 'min_child_weight': 5, 'subsample': 0.9373020172740307, 'colsample_bytree': 0.6347865560176783, 'gamma': 4.657777107011341, 'reg_alpha': 1.1604106664621372, 'reg_lambda': 0.7084726161974768}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:21,897] Trial 95 finished with value: 0.9114424758201581 and parameters: {'n_estimators': 500, 'max_depth': 9, 'learning_rate': 0.267448390552437, 'min_child_weight': 6, 'subsample': 0.9459909165653893, 'colsample_bytree': 0.6762078938160901, 'gamma': 4.517390706497729, 'reg_alpha': 0.7698653769707797, 'reg_lambda': 0.35482986544062967}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:22,145] Trial 96 finished with value: 0.9171465952581831 and parameters: {'n_estimators': 98, 'max_depth': 10, 'learning_rate': 0.21610254725701966, 'min_child_weight': 5, 'subsample': 0.9792070277341125, 'colsample_bytree': 0.6218472575607273, 'gamma': 4.933676638374395, 'reg_alpha': 1.300408378374964, 'reg_lambda': 1.1798445375206474}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:22,877] Trial 97 finished with value: 0.9100057469156182 and parameters: {'n_estimators': 430, 'max_depth': 9, 'learning_rate': 0.15276339315433965, 'min_child_weight': 9, 'subsample': 0.9810816888347529, 'colsample_bytree': 0.6246420119089295, 'gamma': 4.924221980921641, 'reg_alpha': 1.381697983178382, 'reg_lambda': 1.1267428022360308}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:23,110] Trial 98 finished with value: 0.9114485895601776 and parameters: {'n_estimators': 64, 'max_depth': 9, 'learning_rate': 0.16908863660557824, 'min_child_weight': 5, 'subsample': 0.9872639855870308, 'colsample_bytree': 0.5837706039398276, 'gamma': 2.7936785580988275, 'reg_alpha': 1.570599883054082, 'reg_lambda': 1.5314111861293844}. Best is trial 53 with value: 0.9185894379027425.
[I 2026-09-06 12:06:23,347] Trial 99 finished with value: 0.9042832862575353 and parameters: {'n_estimators': 96, 'max_depth': 10, 'learning_rate': 0.21529246624214485, 'min_child_weight': 6, 'subsample': 0.8837789222876513, 'colsample_bytree': 0.5161657344386849, 'gamma': 4.998717914605751, 'reg_alpha': 2.804535930243482, 'reg_lambda': 1.293645823490059}. Best is trial 53 with value: 0.9185894379027425.

In [164]:
best_trial = study2.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'n_estimators': 490, 'max_depth': 10, 'learning_rate': 0.180069769624633, 'min_child_weight': 5, 'subsample': 0.9835158966110434, 'colsample_bytree': 0.5798007763471013, 'gamma': 4.885314530982971, 'reg_alpha': 0.9056875464332528, 'reg_lambda': 0.7400350582594433}
Best trial accuracy: 0.9185894379027425

In [165]:
xg=XGBClassifier(**study2.best_trial.params,random_state=42)
xg.fit(X_train,y_train)
ypred6=xg.predict(X_test)
accuracy_score(ypred6,y_test)

0.87

In [166]:
clf2.feature_importances_

array([0.4263867 , 0.00804417, 0.55413129, 0.01143784])

,name,voterid,age,gender,address,state,district_number,district_name,constituency_name,constituency_number,polling_station_id,polling_station_name,pincode,household_size,distance_from_assigned_polling_booth_km,voted_status
0,Anirudh Srinivas Patibandla,DUMMY-PRG-006144,61,Female,"Prototype Nagar, House 016143, Pargi (Dummy Ad...",Telangana,15,Vikarabad,Pargi,54,PRG-PS-044,Zilla Parishad High School 5,501501,5.0,2.83,1
1,Chetan Teja Nimmala,DUMMY-PRG-018123,22,Female,"Demo Layout, House 028122, Pargi (Dummy Address)",Telangana,15,Vikarabad,Pargi,54,PRG-PS-128,Government Junior College 13,501501,8.0,2.92,0
2,Naveen Penumudi,DUMMY-PRG-074000,21,Female,"Test Residency, House 083999, Pargi (Dummy Add...",Telangana,15,Vikarabad,Pargi,54,PRG-PS-190,District Parishad School 19,501501,7.0,2.25,0
3,Akhil Devi Deshmukh,DUMMY-PRG-020592,25,Male,"Demo Extension, House 030591, Pargi (Dummy Add...",Telangana,15,Vikarabad,Pargi,54,PRG-PS-157,Model School 16,501501,6.0,1.49,0
4,Navin Rani Singireddy,DUMMY-PRG-101083,77,Male,"Dummy Hamlet, House 111082, Pargi (Dummy Address)",Telangana,15,Vikarabad,Pargi,54,PRG-PS-128,Government Junior College 13,501501,5.0,1.46,1